In [161]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [162]:
pd.set_option('display.max_columns', None)

In [ ]:
fdf = pd.read_csv("../data/Delivery Dataset.csv")

df = fdf.copy()

In [164]:
df.shape

(40207, 19)

In [165]:
df.shape

(40207, 19)

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40207 entries, 0 to 40206
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_ID           40207 non-null  object
 1   Delivery_person_Age          38562 non-null  float64
 2   Delivery_person_Ratings      38520 non-null  float64
 3   Restaurant_latitude          40207 non-null  float64
 4   Restaurant_longitude         40207 non-null  float64
 5   Delivery_location_latitude   40207 non-null  float64
 6   Delivery_location_longitude  40207 non-null  float64
 7   Order_Date                   40207 non-null  object
 8   Time_Orderd                  38676 non-null  object
 9   Time_Order_picked            40207 non-null  object
 10  Weather_conditions           39662 non-null  object
 11  Road_traffic_density         39675 non-null  object
 12  Vehicle_condition            40207 non-null  int64
 13  Type_of_order                40207 non-null  object
 14  Type_of_vehicle              40207 non-null  object
 15  multiple_deliveries          39357 non-null  float64
 16  Festival                     40033 non-null  object
 17  City_Type                    39174 non-null  object
 18  Time_taken (min)             40207 non-null  int64
dtypes: float64(7), int64(2), object(10)
memory usage: 5.8+ MB

In [167]:
df

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
0,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40202,BANGRES16DEL03,28.0,4.9,13.029198,77.570997,13.059198,77.600997,30-03-2022,21:55,0.916666667,Sandstorms,Jam,1,Meal,scooter,1.0,No,Metropolitian,29
40203,RANCHIRES16DEL01,35.0,4.2,23.371292,85.327872,23.481292,85.437872,08-03-2022,21:45,21:55,Windy,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33
40204,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
40205,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
40206,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [168]:
round(df.isna().sum()/df.shape[0] * 100 , 2)

Delivery_person_ID             0.00
Delivery_person_Age            4.09
Delivery_person_Ratings        4.20
Restaurant_latitude            0.00
Restaurant_longitude           0.00
Delivery_location_latitude     0.00
Delivery_location_longitude    0.00
Order_Date                     0.00
Time_Orderd                    3.81
Time_Order_picked              0.00
Weather_conditions             1.36
Road_traffic_density           1.32
Vehicle_condition              0.00
Type_of_order                  0.00
Type_of_vehicle                0.00
multiple_deliveries            2.11
Festival                       0.43
City_Type                      2.57
Time_taken (min)               0.00
dtype: float64

In [169]:
df.drop(index= df[df['Delivery_person_ID'].isna()].index , inplace=True)

In [170]:
df.isna().sum()

Delivery_person_ID                0
Delivery_person_Age            1645
Delivery_person_Ratings        1687
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1531
Time_Order_picked                 0
Weather_conditions              545
Road_traffic_density            532
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             850
Festival                        174
City_Type                      1033
Time_taken (min)                  0
dtype: int64

Fetching Valuable Features from `Delivery_person_ID` 

like:

`JAPRES04DEL01`
- **JAP** → City code →**Jaipur**
- **RES04** → Region / hub / zone → **Zone 04**
- **DEL01** → Delivery person → **Agent 01**

In [171]:
df['Delivery_person_ID']

0           DEHRES17DEL01
1           KOCRES16DEL01
2          PUNERES13DEL03
3          LUDHRES15DEL02
4           KNPRES14DEL02
               ...
40202      BANGRES16DEL03
40203    RANCHIRES16DEL01
40204      CHENRES08DEL03
40205     COIMBRES11DEL01
40206    RANCHIRES09DEL02
Name: Delivery_person_ID, Length: 40207, dtype: object

In [172]:
df['Delivery_person_ID'].str[:-10].unique()

array(['DEH', 'KOC', 'PUNE', 'LUDH', 'KNP', 'MUM', 'MYS', 'HYD', 'KOL',
       'RANCHI', 'COIMB', 'CHEN', 'JAP', 'SUR', 'BANG', 'GOA', 'AGR',
       'ALH', 'BANGR', 'VAD', 'AURG', 'AGRR', 'INDO', 'SURR', 'KOCR',
       'MYSR', 'LUDHR', 'DEHR', 'HYDR', 'MUMR', 'RANCHIR', 'JAPR',
       'INDOR', 'CHENR', 'PUNER', 'VADR', 'COIMBR', 'BHP', 'KNPR', 'GOAR',
       'BHPR', 'AURGR', 'KOLR'], dtype=object)

In [173]:
city = df['Delivery_person_ID'].str[:-10].apply(lambda x : x[:-1] if x.endswith("R") else x)
df.insert(1 , "City" , city)

In [174]:
city_mapping = {
    "INDO": "Indore",
    "BANG": "Bangalore",
    "COIMB": "Coimbatore",
    "CHEN": "Chennai",
    "HYD": "Hyderabad",
    "RANCHI": "Ranchi",
    "MYS": "Mysore",
    "DEH": "Dehradun",
    "KOC": "Kochi",
    "PUNE": "Pune",
    "LUDH": "Ludhiana",
    "KNP": "Kanpur",
    "MUM": "Mumbai",
    "KOL": "Kolkata",
    "JAP": "Jaipur",
    "SUR": "Surat",
    "SU": "Surat",
    "GOA": "Goa",
    "AURG": "Aurangabad",
    "AGR": "Agra",
    "AG": "Agra",
    "VAD": "Vadodara",
    "ALH": "Prayagraj",
    "BHP": "Bhopal"
}

In [175]:
df['City'] = df['City'].map(city_mapping)

In [176]:
df['City'].nunique()

22

In [177]:
df.sample()

,Delivery_person_ID,City,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
28700,JAPRES010DEL03,Jaipur,32.0,4.5,26.921411,75.793604,26.981411,75.853604,03-03-2022,17:20,17:35,Sunny,Medium,0,Buffet,motorcycle,0.0,No,Metropolitian,29

In [178]:
zone = df['Delivery_person_ID'].str[-10:-5].str.replace('RES' , "Zone").str.replace('ES010' , "Zone10").str.strip()

df.insert(2 , "Zone" , zone)

In [179]:
df.sample()

,Delivery_person_ID,City,Zone,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
34392,AURGRES07DEL01,Aurangabad,Zone07,26.0,4.7,19.875908,75.358888,19.945908,75.428888,18-02-2022,19:30,19:40,Sunny,Jam,2,Meal,motorcycle,1.0,No,Urban,12

In [180]:
df['Delivery_person_ID'].str[-2:]

0        01
1        01
2        03
3        02
4        02
         ..
40202    03
40203    01
40204    03
40205    01
40206    02
Name: Delivery_person_ID, Length: 40207, dtype: object

In [181]:
agent = df['Delivery_person_ID'].str[-2:].str.strip()   

df.insert(3 , "Delivery_Agent" , agent)

In [182]:
df['Restaurant_latitude'] = df['Restaurant_latitude'].apply(lambda x : -x if x < 0 else x)

df['Restaurant_longitude'] = df['Restaurant_longitude'].apply(lambda x : -x if x < 0 else x)

In [183]:
df.shape

(40207, 22)

In [184]:
px.scatter_geo(
    df,
    lat="Restaurant_latitude",
    lon="Restaurant_longitude"
)

In [185]:
px.scatter_geo(
    df,
    lat="Delivery_location_latitude",
    lon="Delivery_location_longitude"
)

In [186]:
df.isna().sum().loc[lambda x : x > 0]

Delivery_person_Age        1645
Delivery_person_Ratings    1687
Time_Orderd                1531
Weather_conditions          545
Road_traffic_density        532
multiple_deliveries         850
Festival                    174
City_Type                  1033
dtype: int64

In [187]:
df['Delivery_person_Age'].describe()

count    38562.000000
mean        29.644572
std          5.814019
min         15.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

In [188]:
df['Delivery_person_Age'] = df['Delivery_person_Age'].fillna(df['Delivery_person_Age'].mean())

In [189]:
df.isna().sum().loc[lambda x : x > 0]

Delivery_person_Ratings    1687
Time_Orderd                1531
Weather_conditions          545
Road_traffic_density        532
multiple_deliveries         850
Festival                    174
City_Type                  1033
dtype: int64

In [190]:
# Converting DType of Order_Date from object to datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'] , format='mixed')

In [191]:
# Checking what irrelavant values present in Time_Order_picked feature
invalid_mask_time_ordered = pd.to_datetime(df['Time_Orderd'], errors='coerce').isna()

wrong_values_to = df.loc[invalid_mask_time_ordered, 'Time_Orderd']
wrong_values_to.value_counts()

C:\Users\LeoML\AppData\Local\Temp\ipykernel_5916\2467684873.py:2: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Time_Orderd
0.833333333    400
0.791666667    377
0.875          372
1              366
0.958333333    361
0.75           360
0.916666667    355
0.416666667    187
0.458333333    175
0.375          166
0.5            147
0.625           79
0.541666667     74
0.583333333     63
0.708333333     61
0.666666667     46
Name: count, dtype: int64

In [192]:
# Function for time correction as there present 24:05 which is not a valid one so converting into 00:05
def correct_time(t):
    if pd.isna(t):
        return t
    if t.startswith("24:"):
        return "00:"+t.split(":")[1]
    return t

df['Time_Order_picked'] = df['Time_Order_picked'].apply(correct_time)

In [193]:
# Checking what irrelavant values present in Time_Order_picked feature
invalid_mask_time_order_picked = pd.to_datetime(df['Time_Order_picked'], errors='coerce').isna()

wrong_values_top = df.loc[invalid_mask_time_order_picked, 'Time_Order_picked']
wrong_values_top.value_counts()

C:\Users\LeoML\AppData\Local\Temp\ipykernel_5916\837461676.py:2: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Time_Order_picked
0.833333333    407
0.916666667    382
0.875          377
1              374
0.75           372
0.791666667    359
0.958333333    344
0.375          190
0.416666667    182
0.5            142
0.458333333    135
0.625           92
0.666666667     83
0.541666667     75
0.583333333     75
0.708333333     63
Name: count, dtype: int64

In [194]:
# Converting Time_Ordered and Time_Order_picked feature to datetime and also removing irrelavant values like (0.875 , 0.75 , 1 , etc) using `errors = 'coerce'`

df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'],
            format="%H:%M",
            errors='coerce').dt.time

df['Time_Order_picked'] = pd.to_datetime(df['Time_Order_picked'],
            format="%H:%M",
            errors='coerce').dt.time

In [195]:
# Creating order_datetime from Order_Date + Time_Ordered
order_datetime = pd.to_datetime(
    df['Order_Date'].astype('str') + " " + df['Time_Orderd'].astype('str'),
    errors='coerce'
)

df.insert(10 , "Order_Datetime" , order_datetime)

# Creating order_datetime from Order_Date + Time_Order_picked
Pickup_Datetime = pd.to_datetime(
    df['Order_Date'].astype('str') + " " + df['Time_Order_picked'].astype('str'),
    errors='coerce'
)

df.insert(11 , "Pickup_Datetime" , Pickup_Datetime)

In [196]:
# Some of the pickup done overnight (00:05 or 00:10)
mask = df['Pickup_Datetime'] < df['Order_Datetime']

df.loc[mask , 'Pickup_Datetime'] = df.loc[mask , 'Pickup_Datetime'] + pd.Timedelta(days = 1)

In [197]:
# Droping Order_Date , Time_Ordered , Time_Order_Picked as we have designed new freatures from them
df.drop(columns=['Order_Date' , "Time_Orderd" , "Time_Order_picked"] , inplace=True)

In [198]:
# Prep Time 
prep_time_min = ((df['Pickup_Datetime'] - df['Order_Datetime']).dt.total_seconds()/60)

df.insert(12 , "Prep_Time(min)" , prep_time_min)

In [199]:
# Droping these rows because imputation is risky
df.drop(index=df[df['Order_Datetime'].isna() & df['Pickup_Datetime'].isna()].index  , inplace=True)

In [200]:
# Statistical Information of Prep Time Feature
df['Prep_Time(min)'].describe()

count    31577.000000
mean         9.977832
std          4.085072
min          5.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: Prep_Time(min), dtype: float64

In [201]:
# Median Prep Time
median_prep_time = df['Prep_Time(min)'].median()

# imputing the values of Order_Datetime with Pickup_Time Order_Datetime - median 
mask1 = df['Order_Datetime'].isna() 
df.loc[mask1 , "Order_Datetime"] = df.loc[mask1 , "Pickup_Datetime"] - pd.Timedelta(minutes=median_prep_time)

# imputing the values of Pickup_time with Order_Datetime + median 
mask2 = df['Pickup_Datetime'].isna()
df.loc[mask2 , 'Pickup_Datetime'] = df.loc[mask2 , "Order_Datetime"] + pd.Timedelta(minutes=median_prep_time)

In [202]:
# updating the Prep Time 
df['Prep_Time(min)'] = (df['Pickup_Datetime'] - df['Order_Datetime']).dt.total_seconds()/60

In [203]:
df.sample()

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
9458,INDORES010DEL02,Indore,Zone10,02,27.0,4.8,22.75004,75.902847,22.80004,75.952847,2022-05-04 22:20:00,2022-05-04 22:35:00,15.0,Fog,Low,2,Snack,scooter,0.0,No,Metropolitian,13

In [204]:
# These Features are very important for both analysis and prediction and all of them contains null value and when imputing them with some mode (random way) will decrease the efficiency of the model and imputation will become unreliable 


df.drop(index=df[df['Delivery_person_Ratings'].isna() & df['Weather_conditions'].isna() & df['Road_traffic_density'].isna() & df['multiple_deliveries'].isna()].index , inplace=True)


df.drop(index=df[df['Delivery_person_Ratings'].isna() & df['Weather_conditions'].isna() & df['Road_traffic_density'].isna()].index , inplace=True)

In [205]:
# Fill missing values in 'City_Type' using group-wise mode based on 'City'
df['City_Type'] = df.groupby('City')['City_Type']\
        .transform(lambda x : x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))

In [206]:
df['Time_taken (min)'].describe()

count    39642.000000
mean        26.604788
std          9.265927
min         10.000000
25%         19.000000
50%         26.000000
75%         33.000000
max         54.000000
Name: Time_taken (min), dtype: float64

In [207]:
df['Delivery_person_Ratings'].mean()

np.float64(4.630250551733091)

In [208]:
mask3 = df[df['Delivery_person_Ratings'] == 6.0].index
df.loc[mask3 , 'Delivery_person_Ratings'] = np.nan

In [209]:
df['Delivery_person_Ratings'] = df.groupby('City_Type')['Delivery_person_Ratings'].transform(lambda x: x.fillna(x.median()))

In [210]:
df['Delivery_person_Ratings'].isna().sum()

np.int64(0)

In [211]:
indi = df[df['Weather_conditions'].isna()].index

In [212]:
df['Weather_conditions'] = df.groupby("City")['Weather_conditions'].transform(lambda x : x.fillna(x.mode()[0]))

In [213]:
df.loc[indi , 'Weather_conditions'].value_counts()

Weather_conditions
Fog           41
Cloudy        28
Stormy        12
Windy          3
Sandstorms     2
Name: count, dtype: int64

In [214]:
indi2 = df[df['Road_traffic_density'].isna()].index

In [215]:
indi2

Index([ 2077,  2528,  2568,  3130,  4129,  4529,  4702,  4959,  5186,  5628,
        8071,  8380,  8410,  8910,  9612,  9810, 10668, 10836, 12038, 12436,
       13144, 13174, 14035, 14172, 14795, 15105, 15605, 16725, 17089, 17865,
       18716, 18801, 19669, 19779, 20632, 20729, 20866, 21387, 21987, 22311,
       22855, 23017, 23525, 23780, 23952, 24044, 24200, 24684, 24740, 25015,
       25586, 26076, 26186, 26998, 27549, 28195, 28510, 29293, 29583, 30600,
       30836, 31784, 32718, 33235, 33525, 33536, 34085, 34458, 34465, 35480,
       35534, 36379, 37115, 37786],
      dtype='int64')

In [216]:
df['Road_traffic_density'] = df.groupby('City_Type')['Road_traffic_density'].transform(lambda x : x.fillna(x.mode()[0]))

In [217]:
df.loc[indi2 , 'Road_traffic_density'].value_counts()

Road_traffic_density
Jam    56
Low    18
Name: count, dtype: int64

In [218]:
indi3 = df[df['multiple_deliveries'].isna()].index

In [219]:
df['multiple_deliveries'] = df['multiple_deliveries'].fillna(df['multiple_deliveries'].median())

In [220]:
df.loc[indi3 , 'multiple_deliveries']

8        1.0
65       1.0
111      1.0
119      1.0
158      1.0
        ...
39653    1.0
39660    1.0
39756    1.0
39822    1.0
39910    1.0
Name: multiple_deliveries, Length: 834, dtype: float64

In [221]:
df['Festival'] = df['Festival'].transform(lambda x : x.fillna(x.mode()[0]))

In [222]:
df.isna().sum()

Delivery_person_ID             0
City                           0
Zone                           0
Delivery_Agent                 0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Datetime                 0
Pickup_Datetime                0
Prep_Time(min)                 0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City_Type                      0
Time_taken (min)               0
dtype: int64

In [223]:
df.sample()

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
7310,JAPRES12DEL01,Jaipur,Zone12,01,33.0,4.8,26.902908,75.792934,26.942908,75.832934,2022-03-17 14:55:00,2022-03-17 15:10:00,15.0,Cloudy,High,2,Meal,scooter,1.0,No,Metropolitian,25

In [224]:
df

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
0,DEHRES17DEL01,Dehradun,Zone17,01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-12-02 21:55:00,2022-12-02 22:10:00,15.0,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,KOCRES16DEL01,Kochi,Zone16,01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13 14:55:00,2022-02-13 15:05:00,10.0,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,PUNERES13DEL03,Pune,Zone13,03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-04-03 17:30:00,2022-04-03 17:40:00,10.0,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,LUDHRES15DEL02,Ludhiana,Zone15,02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13 09:20:00,2022-02-13 09:30:00,10.0,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,KNPRES14DEL02,Kanpur,Zone14,02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14 19:50:00,2022-02-14 20:05:00,15.0,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40202,BANGRES16DEL03,Bangalore,Zone16,03,28.0,4.9,13.029198,77.570997,13.059198,77.600997,2022-03-30 21:55:00,2022-03-30 22:05:00,10.0,Sandstorms,Jam,1,Meal,scooter,1.0,No,Metropolitian,29
40203,RANCHIRES16DEL01,Ranchi,Zone16,01,35.0,4.2,23.371292,85.327872,23.481292,85.437872,2022-08-03 21:45:00,2022-08-03 21:55:00,10.0,Windy,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33
40204,CHENRES08DEL03,Chennai,Zone08,03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-11-03 23:50:00,2022-11-04 00:05:00,15.0,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
40205,COIMBRES11DEL01,Coimbatore,Zone11,01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-07-03 13:35:00,2022-07-03 13:40:00,5.0,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
40206,RANCHIRES09DEL02,Ranchi,Zone09,02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-02-03 17:10:00,2022-02-03 17:15:00,5.0,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

---

**Changing Data Type**

In [225]:
df['Delivery_Agent'] = df['Delivery_Agent'].astype('Int32')

In [226]:
df['Delivery_person_Age'] = df['Delivery_person_Age'].astype(int)

In [227]:
df

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
0,DEHRES17DEL01,Dehradun,Zone17,1,36,4.2,30.327968,78.046106,30.397968,78.116106,2022-12-02 21:55:00,2022-12-02 22:10:00,15.0,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,KOCRES16DEL01,Kochi,Zone16,1,21,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13 14:55:00,2022-02-13 15:05:00,10.0,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,PUNERES13DEL03,Pune,Zone13,3,23,4.7,18.562450,73.916619,18.652450,74.006619,2022-04-03 17:30:00,2022-04-03 17:40:00,10.0,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,LUDHRES15DEL02,Ludhiana,Zone15,2,34,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13 09:20:00,2022-02-13 09:30:00,10.0,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,KNPRES14DEL02,Kanpur,Zone14,2,24,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14 19:50:00,2022-02-14 20:05:00,15.0,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40202,BANGRES16DEL03,Bangalore,Zone16,3,28,4.9,13.029198,77.570997,13.059198,77.600997,2022-03-30 21:55:00,2022-03-30 22:05:00,10.0,Sandstorms,Jam,1,Meal,scooter,1.0,No,Metropolitian,29
40203,RANCHIRES16DEL01,Ranchi,Zone16,1,35,4.2,23.371292,85.327872,23.481292,85.437872,2022-08-03 21:45:00,2022-08-03 21:55:00,10.0,Windy,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33
40204,CHENRES08DEL03,Chennai,Zone08,3,30,4.9,13.022394,80.242439,13.052394,80.272439,2022-11-03 23:50:00,2022-11-04 00:05:00,15.0,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
40205,COIMBRES11DEL01,Coimbatore,Zone11,1,20,4.7,11.001753,76.986241,11.041753,77.026241,2022-07-03 13:35:00,2022-07-03 13:40:00,5.0,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
40206,RANCHIRES09DEL02,Ranchi,Zone09,2,23,4.9,23.351058,85.325731,23.431058,85.405731,2022-02-03 17:10:00,2022-02-03 17:15:00,5.0,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [228]:
df['Delivery_person_Ratings'].value_counts().sort_index()

Delivery_person_Ratings
1.0      32
2.5      18
2.6      20
2.7      21
2.8      17
2.9      18
3.0       6
3.1      28
3.2      26
3.3      23
3.4      32
3.5     234
3.6     191
3.7     201
3.8     217
3.9     173
4.0     959
4.1    1286
4.2    1286
4.3    1265
4.4    1218
4.5    2926
4.6    6112
4.7    7394
4.8    6265
4.9    6168
5.0    3506
Name: count, dtype: int64

In [229]:
df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].astype('float32')

In [230]:
df['Vehicle_condition'].value_counts()

Vehicle_condition
0    13416
1    13103
2    13049
3       74
Name: count, dtype: int64

In [231]:
mapping = {
    0:"poor",
    1:"Average",
    2:"Good",
    3:"Excellent",
}

df['Vehicle_condition'] = df['Vehicle_condition'].map(mapping)

In [232]:
df['Vehicle_condition']

0           Good
1        Average
2        Average
3           poor
4        Average
          ...
40202    Average
40203       Good
40204    Average
40205       poor
40206       Good
Name: Vehicle_condition, Length: 39642, dtype: object

In [233]:
df['Prep_Time(min)'] = df['Prep_Time(min)'].astype('Float32')

In [234]:
df['multiple_deliveries'] = df['multiple_deliveries'].astype('Int8')

In [235]:
df['Prep_Time(min)'] = df['Prep_Time(min)'].astype('Int16')

In [236]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39642 entries, 0 to 40206
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_ID           39642 non-null  object
 1   City                         39642 non-null  object
 2   Zone                         39642 non-null  object
 3   Delivery_Agent               39642 non-null  Int32
 4   Delivery_person_Age          39642 non-null  int64
 5   Delivery_person_Ratings      39642 non-null  float32
 6   Restaurant_latitude          39642 non-null  float64
 7   Restaurant_longitude         39642 non-null  float64
 8   Delivery_location_latitude   39642 non-null  float64
 9   Delivery_location_longitude  39642 non-null  float64
 10  Order_Datetime               39642 non-null  datetime64[ns]
 11  Pickup_Datetime              39642 non-null  datetime64[ns]
 12  Prep_Time(min)               39642 non-null  Int16
 13  Weather_conditions           39642 non-null  object
 14  Road_traffic_density         39642 non-null  object
 15  Vehicle_condition            39642 non-null  object
 16  Type_of_order                39642 non-null  object
 17  Type_of_vehicle              39642 non-null  object
 18  multiple_deliveries          39642 non-null  Int8
 19  Festival                     39642 non-null  object
 20  City_Type                    39642 non-null  object
 21  Time_taken (min)             39642 non-null  int64
dtypes: Int16(1), Int32(1), Int8(1), datetime64[ns](2), float32(1), float64(4), int64(2), object(10)
memory usage: 7.3+ MB

In [237]:
df.isna().sum()

Delivery_person_ID             0
City                           0
Zone                           0
Delivery_Agent                 0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Datetime                 0
Pickup_Datetime                0
Prep_Time(min)                 0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City_Type                      0
Time_taken (min)               0
dtype: int64

In [238]:
import numpy as np

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius (km)

    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

distance_km = round(haversine(
    df["Restaurant_latitude"],
    df["Restaurant_longitude"],
    df["Delivery_location_latitude"],
    df["Delivery_location_longitude"]
), 2)

df.insert( df.columns.get_loc("Delivery_location_longitude") + 1, "distance_km", distance_km)

In [239]:
df.drop(columns=['Prep_Time(min)' , 'Delivery_person_ID'] , inplace=True)

In [240]:
df.to_csv("data/Cleaned Delivery Dataset.csv" , index=False)