In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV , KFold , cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
from sklearn.compose import ColumnTransformer , TransformedTargetRegressor
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder , PowerTransformer
from sklearn.base import BaseEstimator , TransformerMixin
import optuna
from lightgbm import LGBMRegressor
import mlflow
import dagshub
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_parallel_coordinate , plot_slice

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
dagshub.init(repo_owner="mridul0010" , repo_name="Delivery-Time-Analysis-Prediction" , mlflow=True)

Accessing as mridul0010

Initialized MLflow to track repo "mridul0010/Delivery-Time-Analysis-Prediction"

Repository mridul0010/Delivery-Time-Analysis-Prediction initialized!

In [ ]:
mlflow.set_tracking_uri("https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow")

In [ ]:
mlflow.set_experiment("Hyperparameter Tuning - RF")

2026/07/02 00:31:19 INFO mlflow.tracking.fluent: Experiment with name 'Hyperparameter Tuning - RF' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/262c557fd773426192260f6ce2aaf745', creation_time=1782932481027, effective_trace_archival_retention=None, experiment_id='0', last_update_time=1782932481027, lifecycle_stage='active', name='Hyperparameter Tuning - RF', tags={}, trace_location=None, workspace='default'>

In [ ]:
df = pd.read_csv('../data/Cleaned Delivery Dataset.csv')

In [ ]:
pd.set_option('display.max_columns' , None)

In [ ]:
df.drop(columns=['Delivery_Agent'] , inplace=True)

In [ ]:
df['Order_Datetime'] = pd.to_datetime(df['Order_Datetime'])
df['Pickup_Datetime'] = pd.to_datetime(df['Pickup_Datetime'])

In [ ]:
class FeatureEngineering(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.rating_bins = None

    def fit(self, X, y=None):
        X = X.copy()
        
        # Store bins for consistent transformation
        self.rating_bins = pd.qcut(
            X['Delivery_person_Ratings'],
            q=3,
            retbins=True,
            duplicates='drop'
        )[1]
        
        return self

    def transform(self, X):
        X = X.copy()

        # Datetime conversion
        X['Order_Datetime'] = pd.to_datetime(X['Order_Datetime'], errors='coerce')
        X['Pickup_Datetime'] = pd.to_datetime(X['Pickup_Datetime'], errors='coerce')

        # Rating group
        X["delivery_rating_group"] = pd.cut(
            X['Delivery_person_Ratings'],
            bins=self.rating_bins,
            labels=['Low', 'Medium', 'High'],
            include_lowest=True
        )

        # Age group
        X["age_group"] = pd.cut(
            X['Delivery_person_Age'],
            bins=[14, 25, 35, 60],
            labels=['Young', 'Adult', 'Senior']
        )

        # Distance group
        X["distance_group"] = pd.cut(
            X['distance_km'],
            bins=[0, 5, 10, 25],
            labels=['Short Distance', 'Medium Distance', 'Long Distance']
        )

        # Time features
        X['Prep_Time(min)'] = (
            X['Pickup_Datetime'] - X['Order_Datetime']
        ).dt.total_seconds() / 60

        X['Order_hour'] = X['Order_Datetime'].dt.hour
        X['Order_day'] = X['Order_Datetime'].dt.day_name()

        X['isWeekend'] = X['Order_day'].isin(["Saturday", "Sunday"]).astype(int)

        X['Time_Of_Day'] = pd.cut(
            X['Order_hour'],
            bins=[0, 6, 12, 18, 24],
            labels=["Night", "Morning", "Afternoon", "Evening"],
            include_lowest=True
        )

        # Drop raw datetime
        X = X.drop(columns=['Order_Datetime', 'Pickup_Datetime'], errors='ignore')

        return X

    def get_feature_names_out(self , input_features = None):
        return input_features

In [ ]:
X = df.drop(columns=['Time_taken (min)'])
y = df['Time_taken (min)']

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [ ]:
X

,City,Zone,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,distance_km,Order_Datetime,Pickup_Datetime,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type
0,Dehradun,Zone17,36,4.2,30.327968,78.046106,30.397968,78.116106,10.28,2022-12-02 21:55:00,2022-12-02 22:10:00,Fog,Jam,Good,Snack,motorcycle,3,No,Metropolitian
1,Kochi,Zone16,21,4.7,10.003064,76.307589,10.043064,76.347589,6.24,2022-02-13 14:55:00,2022-02-13 15:05:00,Stormy,High,Average,Meal,motorcycle,1,No,Metropolitian
2,Pune,Zone13,23,4.7,18.562450,73.916619,18.652450,74.006619,13.79,2022-04-03 17:30:00,2022-04-03 17:40:00,Sandstorms,Medium,Average,Drinks,scooter,1,No,Metropolitian
3,Ludhiana,Zone15,34,4.3,30.899584,75.809346,30.919584,75.829346,2.93,2022-02-13 09:20:00,2022-02-13 09:30:00,Sandstorms,Low,poor,Buffet,motorcycle,0,No,Metropolitian
4,Kanpur,Zone14,24,4.7,26.463504,80.372929,26.593504,80.502929,19.40,2022-02-14 19:50:00,2022-02-14 20:05:00,Fog,Jam,Average,Snack,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39637,Bangalore,Zone16,28,4.9,13.029198,77.570997,13.059198,77.600997,4.66,2022-03-30 21:55:00,2022-03-30 22:05:00,Sandstorms,Jam,Average,Meal,scooter,1,No,Metropolitian
39638,Ranchi,Zone16,35,4.2,23.371292,85.327872,23.481292,85.437872,16.60,2022-08-03 21:45:00,2022-08-03 21:55:00,Windy,Jam,Good,Drinks,motorcycle,1,No,Metropolitian
39639,Chennai,Zone08,30,4.9,13.022394,80.242439,13.052394,80.272439,4.66,2022-11-03 23:50:00,2022-11-04 00:05:00,Cloudy,Low,Average,Drinks,scooter,0,No,Metropolitian
39640,Coimbatore,Zone11,20,4.7,11.001753,76.986241,11.041753,77.026241,6.23,2022-07-03 13:35:00,2022-07-03 13:40:00,Cloudy,High,poor,Snack,motorcycle,1,No,Metropolitian
39641,Ranchi,Zone09,23,4.9,23.351058,85.325731,23.431058,85.405731,12.07,2022-02-03 17:10:00,2022-02-03 17:15:00,Fog,Medium,Good,Snack,scooter,1,No,Metropolitian

In [ ]:
numerical = ['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 
       'multiple_deliveries', 'distance_km', 'Prep_Time(min)', 'Order_hour',
       'isWeekend']

ohe_col = ['City', 'Zone', 'Weather_conditions',
       'Type_of_order', 'Type_of_vehicle',
       'City_Type','Order_day', 'Time_Of_Day']

ordinal_col = ['Road_traffic_density' , 'Vehicle_condition' , 'Festival',
       'delivery_rating_group' , 'age_group' , 'distance_group']

In [ ]:
transformer = ColumnTransformer(
    transformers=[
        ("ohe" , OneHotEncoder(sparse_output=False , handle_unknown='ignore') , ohe_col),
        ('oe' , OrdinalEncoder(categories=[
            ['Low', 'Medium', 'High', 'Jam'],                         # Road_traffic_density
            ['poor', 'Average', 'Good' , 'Excellent'],                # Vehicle_condition
            ['No', 'Yes'],                                            # Festival
            ['Low', 'Medium', 'High'],                                # delivery_rating_group
            ['Young', 'Adult', 'Senior'],                             # age_group
            ['Short Distance', 'Medium Distance', 'Long Distance']    # distance_group
        ]) , ordinal_col),
        ('Scaling' , StandardScaler() , numerical)
    ],remainder='passthrough'
)

In [ ]:
pipeline = Pipeline(
    [
        ("FeatureEngineering" , FeatureEngineering()),
        ("ColumnTransformer" , transformer)
    ]
)

In [ ]:
X_train_trans = pipeline.fit_transform(X_train)
X_test_trans = pipeline.transform(X_test)

In [ ]:
pt = PowerTransformer()

In [ ]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            # Number of trees in the forest
            "n_estimators": trial.suggest_int("n_estimators", 50, 300),
            
            # Maximum depth of the tree
            "max_depth": trial.suggest_int("max_depth", 2, 32),
            
            # Minimum number of samples required to split an internal node
            "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
            
            # Minimum number of samples required to be at a leaf node
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20),
            
            # Number of features to consider when looking for the best split
            "max_features": trial.suggest_float("max_features", 0.1, 1.0),
            
            # Whether bootstrap samples are used when building trees
            "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
            
            "random_state": 42,
            "n_jobs": -1,
        }

        # log params
        mlflow.log_params(params)


        rf = RandomForestRegressor(**params)
        model = TransformedTargetRegressor(regressor=rf , transformer=pt)

        model.fit(X_train_trans , y_train)

        cv_score = cross_val_score(
            model ,
            X_train_trans , 
            y_train , 
            cv=10 , 
            scoring="neg_mean_absolute_error",
            n_jobs=-1
        )

        mean_score = -(cv_score.mean())

        # log avg cross val error
        mlflow.log_metric("cross_val_error" , mean_score)

        return mean_score

In [ ]:
study = optuna.create_study(direction='minimize')

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective , n_trials=50 , n_jobs=-1 , show_progress_bar=True)

    # log the best params
    mlflow.log_params(study.best_params)

    # log best score
    mlflow.log_metric("best_score" , study.best_value)

    # training the lgbm on best param
    best_rf = RandomForestRegressor(**study.best_params)

    best_model = TransformedTargetRegressor(regressor=best_rf , transformer=pt)

    best_model.fit(X_train_trans , y_train)

    y_pred_train = best_model.predict(X_train_trans)
    y_pred_test = best_model.predict(X_test_trans)

    scores = cross_val_score(
        best_model,
        X_train_trans,
        y_train,
        scoring="neg_mean_absolute_error",
        cv=5,n_jobs=-1
    )

    # logging metrics
    mlflow.log_metric("Training_error" ,mean_absolute_error(y_train ,y_pred_train))
    mlflow.log_metric("Test_error" ,mean_absolute_error(y_test ,y_pred_test))
    mlflow.log_metric("Training_r2" ,r2_score(y_train ,y_pred_train))
    mlflow.log_metric("Test_r2" ,r2_score(y_test ,y_pred_test))
    mlflow.log_metric("cross_val" , -scores.mean())

    # Generate the optuna plots
    fig_history = plot_optimization_history(study)
    fig_parallel = plot_parallel_coordinate(study)
    fig_importance = plot_param_importances(study)
    fig_slice = plot_slice(study)

    # Loginf plots
    mlflow.log_figure(fig_history, "optuna_plots/optimization_history.html")
    mlflow.log_figure(fig_importance, "optuna_plots/param_importances.html")
    mlflow.log_figure(fig_parallel, "optuna_plots/parallel_coordinate.html")
    mlflow.log_figure(fig_slice, "optuna_plots/plot_slice.html")
    
    # log the best model 
    mlflow.sklearn.log_model(best_rf , artifact_path="model_RF")

[I 2026-07-02 00:31:20,444] A new study created in memory with name: no-name-c9bda206-13d4-49ee-ab1e-c01c51a68d72
  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run resilient-shad-423 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/8970ac84fb3640e795668685b67138c3
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 12. Best value: 4.06613:   2%|▏         | 1/50 [02:12<1:48:18, 132.61s/it]

[I 2026-07-02 00:33:33,757] Trial 12 finished with value: 4.066134063951305 and parameters: {'n_estimators': 111, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 16, 'max_features': 0.2511049179853957, 'bootstrap': True}. Best is trial 12 with value: 4.066134063951305.
🏃 View run peaceful-mare-906 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/5eeb35af30ad405eb3343d873b311e95
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:   4%|▍         | 2/50 [02:17<46:12, 57.75s/it]

[I 2026-07-02 00:33:39,105] Trial 1 finished with value: 3.0611508050761493 and parameters: {'n_estimators': 253, 'max_depth': 14, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': 0.5477226664253656, 'bootstrap': True}. Best is trial 1 with value: 3.0611508050761493.
🏃 View run respected-shad-896 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/fed2a7ba214645398de8ec5820c0de7e
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:   6%|▌         | 3/50 [02:35<30:49, 39.35s/it]

[I 2026-07-02 00:33:56,550] Trial 2 finished with value: 3.0763811861265187 and parameters: {'n_estimators': 242, 'max_depth': 28, 'min_samples_split': 16, 'min_samples_leaf': 20, 'max_features': 0.5923881083187326, 'bootstrap': False}. Best is trial 1 with value: 3.0611508050761493.
🏃 View run inquisitive-loon-794 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/584d4edc22524fd5a051e82605ec6f70
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:   8%|▊         | 4/50 [05:02<1:02:40, 81.74s/it]

[I 2026-07-02 00:36:23,284] Trial 15 finished with value: 4.374952247906237 and parameters: {'n_estimators': 59, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_features': 0.1530128829852697, 'bootstrap': True}. Best is trial 1 with value: 3.0611508050761493.
🏃 View run skittish-moth-753 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/0ad8aebddafa4978abcb0dc6989f56ba
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:  10%|█         | 5/50 [05:10<41:29, 55.32s/it]

[I 2026-07-02 00:36:31,759] Trial 0 finished with value: 3.0729655940976595 and parameters: {'n_estimators': 165, 'max_depth': 18, 'min_samples_split': 17, 'min_samples_leaf': 17, 'max_features': 0.5752017157329207, 'bootstrap': False}. Best is trial 1 with value: 3.0611508050761493.
🏃 View run omniscient-shrew-278 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/0bbb92cf949d4a4584b0ea1e79a35773
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:  12%|█▏        | 6/50 [05:17<28:34, 38.97s/it]

[I 2026-07-02 00:36:38,998] Trial 7 finished with value: 4.271203648691617 and parameters: {'n_estimators': 145, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 20, 'max_features': 0.9425235236757616, 'bootstrap': False}. Best is trial 1 with value: 3.0611508050761493.
🏃 View run wise-koi-796 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/08dd34899f7049a1a334763c54a29f61
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:  14%|█▍        | 7/50 [05:20<19:31, 27.24s/it]

[I 2026-07-02 00:36:42,073] Trial 6 finished with value: 5.74991691333207 and parameters: {'n_estimators': 129, 'max_depth': 2, 'min_samples_split': 18, 'min_samples_leaf': 12, 'max_features': 0.6613521857155065, 'bootstrap': True}. Best is trial 1 with value: 3.0611508050761493.
🏃 View run peaceful-ox-557 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/d9288c9ad350461abb09d5b700b8b46a
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 1. Best value: 3.06115:  16%|█▌        | 8/50 [05:25<14:03, 20.09s/it]

🏃 View run intelligent-bat-336 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/f9099c53d0964e5d87f7d1a91dd316d5
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0
[I 2026-07-02 00:36:46,851] Trial 4 finished with value: 3.0710983195122226 and parameters: {'n_estimators': 147, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.29399242654237256, 'bootstrap': True}. Best is trial 1 with value: 3.0611508050761493.

Best trial: 5. Best value: 3.05778:  18%|█▊        | 9/50 [05:26<09:31, 13.95s/it]

[I 2026-07-02 00:36:47,293] Trial 5 finished with value: 3.057779395351624 and parameters: {'n_estimators': 255, 'max_depth': 21, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 0.28047993069736565, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run honorable-hound-486 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/93f9f7dbbf634b77a4dd1b3fc580f693
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  20%|██        | 10/50 [05:27<06:46, 10.16s/it]

[I 2026-07-02 00:36:48,905] Trial 13 finished with value: 3.2847167590913116 and parameters: {'n_estimators': 107, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 11, 'max_features': 0.2624739729136462, 'bootstrap': True}. Best is trial 5 with value: 3.057779395351624.
🏃 View run inquisitive-kit-760 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/9abbe75adc43459a9421503149dee187
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  22%|██▏       | 11/50 [05:37<06:28,  9.95s/it]

[I 2026-07-02 00:36:58,453] Trial 8 finished with value: 3.1620212072951643 and parameters: {'n_estimators': 173, 'max_depth': 22, 'min_samples_split': 10, 'min_samples_leaf': 12, 'max_features': 0.8787038044222276, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run angry-ray-621 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/ef9723a590134494b494a64a857dab60
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  24%|██▍       | 12/50 [05:41<05:10,  8.17s/it]

[I 2026-07-02 00:37:02,550] Trial 10 finished with value: 3.5250713077810873 and parameters: {'n_estimators': 226, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 11, 'max_features': 0.4163886091362663, 'bootstrap': True}. Best is trial 5 with value: 3.057779395351624.
🏃 View run stylish-bat-693 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/c92b1dd2e3d64dd592eee9ff5a23b6e2
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  26%|██▌       | 13/50 [05:50<05:11,  8.42s/it]

[I 2026-07-02 00:37:11,555] Trial 11 finished with value: 3.199006409393966 and parameters: {'n_estimators': 259, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 19, 'max_features': 0.17464365305187607, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run bouncy-sloth-725 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/b414a0f8029f415faf5094f728961588
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  28%|██▊       | 14/50 [05:55<04:22,  7.30s/it]

[I 2026-07-02 00:37:16,273] Trial 9 finished with value: 3.063235648248239 and parameters: {'n_estimators': 175, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 18, 'max_features': 0.3785425208564501, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run nosy-ox-937 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/93826515c27042bf8b316f83549d4821
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  30%|███       | 15/50 [06:41<11:06, 19.03s/it]

[I 2026-07-02 00:38:02,433] Trial 14 finished with value: 3.0650570217040713 and parameters: {'n_estimators': 174, 'max_depth': 31, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.7038729655363783, 'bootstrap': True}. Best is trial 5 with value: 3.057779395351624.
🏃 View run victorious-calf-113 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/7c010176974b4216917a550470e3c3ef
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  32%|███▏      | 16/50 [07:26<15:09, 26.75s/it]

[I 2026-07-02 00:38:47,102] Trial 3 finished with value: 3.072054317505745 and parameters: {'n_estimators': 201, 'max_depth': 25, 'min_samples_split': 13, 'min_samples_leaf': 11, 'max_features': 0.7562407641064941, 'bootstrap': True}. Best is trial 5 with value: 3.057779395351624.
🏃 View run zealous-moth-408 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/a940dca2abf64f66a07fcafc03e549f5
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  34%|███▍      | 17/50 [07:39<12:35, 22.91s/it]

[I 2026-07-02 00:39:01,129] Trial 16 finished with value: 4.642181034614986 and parameters: {'n_estimators': 273, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 0.36398788948313976, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run treasured-bug-476 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/567576aca2594690b356563419e85b5f
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  36%|███▌      | 18/50 [08:29<16:31, 30.98s/it]

[I 2026-07-02 00:39:50,895] Trial 17 finished with value: 3.0834801808996977 and parameters: {'n_estimators': 199, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 15, 'max_features': 0.8532367142572557, 'bootstrap': True}. Best is trial 5 with value: 3.057779395351624.
🏃 View run crawling-dog-16 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/60acfc13fff34b50b7255931ae1cc087
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  38%|███▊      | 19/50 [08:55<15:07, 29.28s/it]

[I 2026-07-02 00:40:16,202] Trial 19 finished with value: 3.176508582519193 and parameters: {'n_estimators': 64, 'max_depth': 9, 'min_samples_split': 19, 'min_samples_leaf': 13, 'max_features': 0.6428596712494175, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run delicate-toad-223 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/82097783efca44d7bd7528f187b49c7f
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  40%|████      | 20/50 [08:59<10:52, 21.74s/it]

[I 2026-07-02 00:40:20,387] Trial 18 finished with value: 3.067796493238396 and parameters: {'n_estimators': 212, 'max_depth': 21, 'min_samples_split': 20, 'min_samples_leaf': 20, 'max_features': 0.40555306710337735, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run ambitious-wolf-536 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/2dc218b0f9a64aa3b9cc41dd6810ac2c
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  42%|████▏     | 21/50 [09:06<08:27, 17.49s/it]

[I 2026-07-02 00:40:27,961] Trial 21 finished with value: 5.764537203509718 and parameters: {'n_estimators': 170, 'max_depth': 2, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.4220446297109143, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run youthful-bass-414 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/880b759b427648d88e1e9f0d68919f75
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  44%|████▍     | 22/50 [09:28<08:42, 18.66s/it]

[I 2026-07-02 00:40:49,365] Trial 22 finished with value: 3.0754123840375867 and parameters: {'n_estimators': 78, 'max_depth': 22, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.34831148180388394, 'bootstrap': True}. Best is trial 5 with value: 3.057779395351624.
🏃 View run melodic-skunk-808 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/f670bbf092bc4f3e852d6e7fc4236091
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  46%|████▌     | 23/50 [09:51<08:58, 19.95s/it]

[I 2026-07-02 00:41:12,304] Trial 24 finished with value: 3.217194229939909 and parameters: {'n_estimators': 289, 'max_depth': 18, 'min_samples_split': 16, 'min_samples_leaf': 2, 'max_features': 0.11862262665953706, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run luxuriant-lamb-121 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/d7fbb94000834b9495b67e32f945c2d7
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  48%|████▊     | 24/50 [10:47<13:19, 30.77s/it]

[I 2026-07-02 00:42:08,314] Trial 20 finished with value: 3.1159325700311427 and parameters: {'n_estimators': 140, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 0.7724244019687665, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run nervous-lynx-577 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/501516741b634f12a3d429a1d1ddaf8b
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  50%|█████     | 25/50 [10:58<10:26, 25.05s/it]

[I 2026-07-02 00:42:19,989] Trial 23 finished with value: 3.1603110548986155 and parameters: {'n_estimators': 60, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 16, 'max_features': 0.8895985719443035, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run rogue-sheep-282 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/15c8e056a7544963930ed40a03f83c45
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 5. Best value: 3.05778:  52%|█████▏    | 26/50 [11:59<14:17, 35.71s/it]

[I 2026-07-02 00:43:20,608] Trial 25 finished with value: 3.0695474970738745 and parameters: {'n_estimators': 219, 'max_depth': 23, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.4059777046864001, 'bootstrap': False}. Best is trial 5 with value: 3.057779395351624.
🏃 View run charming-boar-665 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/af7496bf0ed54244a293563d8b99ada5
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 26. Best value: 3.0378:  54%|█████▍    | 27/50 [13:16<18:26, 48.12s/it]

[I 2026-07-02 00:44:37,674] Trial 26 finished with value: 3.0378003999890035 and parameters: {'n_estimators': 271, 'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.4555663224469467, 'bootstrap': False}. Best is trial 26 with value: 3.0378003999890035.
🏃 View run amazing-hare-731 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/bcf2f15a3b6441feb2da9dfd7526b10d
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 26. Best value: 3.0378:  56%|█████▌    | 28/50 [14:17<19:00, 51.84s/it]

[I 2026-07-02 00:45:38,181] Trial 29 finished with value: 3.0809908572406792 and parameters: {'n_estimators': 298, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': 0.740759969555132, 'bootstrap': False}. Best is trial 26 with value: 3.0378003999890035.
🏃 View run adventurous-ant-325 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/b2df1fd1ed1944e7b6c4af03235adff8
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 26. Best value: 3.0378:  58%|█████▊    | 29/50 [15:32<20:35, 58.85s/it]

[I 2026-07-02 00:46:53,386] Trial 27 finished with value: 3.0837373743759544 and parameters: {'n_estimators': 287, 'max_depth': 13, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 0.74159572146567, 'bootstrap': False}. Best is trial 26 with value: 3.0378003999890035.
🏃 View run enthused-koi-740 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/fdce883173d84303ae7845b8a31f185e
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 30. Best value: 3.0349:  60%|██████    | 30/50 [16:20<18:34, 55.73s/it]

[I 2026-07-02 00:47:41,830] Trial 30 finished with value: 3.0349049075200827 and parameters: {'n_estimators': 300, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 0.43443581842073675, 'bootstrap': False}. Best is trial 30 with value: 3.0349049075200827.
🏃 View run bedecked-lynx-71 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/8e3cc89fd64941a6bbbe00b150e695e8
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 30. Best value: 3.0349:  62%|██████▏   | 31/50 [17:34<19:19, 61.03s/it]

[I 2026-07-02 00:48:55,250] Trial 28 finished with value: 3.089074147106776 and parameters: {'n_estimators': 294, 'max_depth': 13, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 0.7492105770924599, 'bootstrap': False}. Best is trial 30 with value: 3.0349049075200827.
🏃 View run redolent-fawn-135 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/fd193fb2ece04796b6888d1e4a0f6e22
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 31. Best value: 3.0344:  64%|██████▍   | 32/50 [18:30<17:54, 59.67s/it]

[I 2026-07-02 00:49:51,729] Trial 31 finished with value: 3.0344026079660855 and parameters: {'n_estimators': 298, 'max_depth': 14, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.46216104866712493, 'bootstrap': False}. Best is trial 31 with value: 3.0344026079660855.
🏃 View run incongruous-hen-446 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/67e6f59c08374312920493cd80cee351
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 31. Best value: 3.0344:  66%|██████▌   | 33/50 [18:45<13:04, 46.14s/it]

[I 2026-07-02 00:50:06,315] Trial 32 finished with value: 3.0451309800524666 and parameters: {'n_estimators': 294, 'max_depth': 12, 'min_samples_split': 19, 'min_samples_leaf': 2, 'max_features': 0.48939183741018144, 'bootstrap': False}. Best is trial 31 with value: 3.0344026079660855.
🏃 View run nebulous-stoat-850 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/de2b75ceef83452289819df036b9e4be
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  68%|██████▊   | 34/50 [19:51<13:55, 52.24s/it]

[I 2026-07-02 00:51:12,773] Trial 33 finished with value: 3.032367779461439 and parameters: {'n_estimators': 299, 'max_depth': 13, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 0.44603640869435546, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run salty-hog-881 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/a25e6c01547f4793a3724dd202074ee1
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  70%|███████   | 35/50 [21:01<14:25, 57.67s/it]

[I 2026-07-02 00:52:23,105] Trial 34 finished with value: 3.0405206789315873 and parameters: {'n_estimators': 291, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 0.5044175744620824, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run treasured-cod-291 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/cb51ffcc31b145f18d0260dcd516af32
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  72%|███████▏  | 36/50 [21:26<11:07, 47.70s/it]

[I 2026-07-02 00:52:47,392] Trial 35 finished with value: 3.0431515042210657 and parameters: {'n_estimators': 281, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': 0.516595003708815, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run defiant-shad-661 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/840087348dda4c5ca12fafa35822c73f
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  74%|███████▍  | 37/50 [24:20<18:31, 85.53s/it]

[I 2026-07-02 00:55:41,366] Trial 36 finished with value: 3.048812810192201 and parameters: {'n_estimators': 274, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.48520799850382934, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run masked-fox-406 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/a58120f2531041418b03c00d90d9a4ef
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  76%|███████▌  | 38/50 [24:26<12:20, 61.69s/it]

[I 2026-07-02 00:55:47,324] Trial 37 finished with value: 3.0471804867704377 and parameters: {'n_estimators': 298, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 0.4842453266458125, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run placid-fly-507 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/64eb8b4057254fcd892281236d41b7b6
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  78%|███████▊  | 39/50 [26:01<13:10, 71.87s/it]

[I 2026-07-02 00:57:23,049] Trial 38 finished with value: 3.0471687138293584 and parameters: {'n_estimators': 295, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 0.4932148986162449, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run clean-trout-740 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/e44847fe0955425c83a7c7f1a04cf967
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  80%|████████  | 40/50 [27:11<11:51, 71.20s/it]

[I 2026-07-02 00:58:32,680] Trial 39 finished with value: 3.051999885066214 and parameters: {'n_estimators': 298, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 0.47829861723436556, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run popular-pig-677 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/d7100a11275946d4b46a851739b837cf
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  82%|████████▏ | 41/50 [27:12<07:32, 50.27s/it]

[I 2026-07-02 00:58:34,115] Trial 40 finished with value: 3.047471944413823 and parameters: {'n_estimators': 295, 'max_depth': 14, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 0.4789911061222425, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run delightful-gnu-862 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/1c7d6c32209e4a369366945924183e98
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  84%|████████▍ | 42/50 [28:28<07:42, 57.83s/it]

[I 2026-07-02 00:59:49,583] Trial 41 finished with value: 3.051936904558819 and parameters: {'n_estimators': 296, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5205087788280225, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run stylish-fish-33 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/e80dd3ca27a74003ae94549a9f268397
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  86%|████████▌ | 43/50 [29:12<06:16, 53.81s/it]

[I 2026-07-02 01:00:34,025] Trial 43 finished with value: 3.0630620277273555 and parameters: {'n_estimators': 251, 'max_depth': 15, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': 0.490461927657329, 'bootstrap': True}. Best is trial 33 with value: 3.032367779461439.
🏃 View run honorable-squid-425 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/d71d13b22e8947aebee3405f8d1ff4c7
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  88%|████████▊ | 44/50 [29:15<03:51, 38.56s/it]

[I 2026-07-02 01:00:36,993] Trial 42 finished with value: 3.0486900026046184 and parameters: {'n_estimators': 299, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 0.49625461557900113, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run redolent-hound-750 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/716747192083417a83675a84e2b44ec7
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  90%|█████████ | 45/50 [30:00<03:21, 40.29s/it]

[I 2026-07-02 01:01:21,307] Trial 44 finished with value: 3.0655485805841787 and parameters: {'n_estimators': 256, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 0.5032348266065901, 'bootstrap': True}. Best is trial 33 with value: 3.032367779461439.
🏃 View run thoughtful-conch-389 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/f68d3be713c3492383e061b072404c76
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  92%|█████████▏| 46/50 [30:35<02:35, 38.84s/it]

[I 2026-07-02 01:01:56,763] Trial 45 finished with value: 3.0485414422743755 and parameters: {'n_estimators': 271, 'max_depth': 16, 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_features': 0.48229863819758834, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run nosy-flea-895 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/b37c43317725429b9a94d68c4b93d6b7
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  94%|█████████▍| 47/50 [31:32<02:12, 44.24s/it]

[I 2026-07-02 01:02:53,595] Trial 46 finished with value: 3.0542529823656372 and parameters: {'n_estimators': 259, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 8, 'max_features': 0.48646513605680675, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run wise-ape-866 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/3d6174884a2c46f584fc54a5c6f80036
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  96%|█████████▌| 48/50 [32:15<01:28, 44.02s/it]

[I 2026-07-02 01:03:37,125] Trial 47 finished with value: 3.0441261573432343 and parameters: {'n_estimators': 269, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 0.5000880581543665, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run delightful-gnu-680 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/daa90acb025b4789b6829fe58b2e32a6
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237:  98%|█████████▊| 49/50 [32:48<00:40, 40.58s/it]

[I 2026-07-02 01:04:09,679] Trial 48 finished with value: 3.047789164134227 and parameters: {'n_estimators': 275, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 0.49057667375280534, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.
🏃 View run intrigued-shark-391 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/26a9ff26be8248d49b5b12b7cb43c0e7
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

Best trial: 33. Best value: 3.03237: 100%|██████████| 50/50 [33:09<00:00, 39.80s/it]

[I 2026-07-02 01:04:30,939] Trial 49 finished with value: 3.0478927903452697 and parameters: {'n_estimators': 272, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 0.48561750394769165, 'bootstrap': False}. Best is trial 33 with value: 3.032367779461439.

2026/07/02 01:05:45 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/02 01:05:49 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0/runs/9949d7127ba241fc8de57c04e09916ee
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/0

In [ ]:
study.best_value

3.032367779461439

In [ ]:
study.best_params

{'n_estimators': 299,
 'max_depth': 13,
 'min_samples_split': 20,
 'min_samples_leaf': 2,
 'max_features': 0.44603640869435546,
 'bootstrap': False}

In [ ]:
best_rf = RandomForestRegressor(**study.best_params)

model = TransformedTargetRegressor(regressor=best_rf , transformer=pt)

model.fit(X_train_trans , y_train)

TransformedTargetRegressor(regressor=RandomForestRegressor(bootstrap=False,
                                                           max_depth=13,
                                                           max_features=0.44603640869435546,
                                                           min_samples_leaf=2,
                                                           min_samples_split=20,
                                                           n_estimators=299),
                           transformer=PowerTransformer())

In [ ]:
y_pred = model.predict(X_test_trans)

r2_score(y_test , y_pred)

0.8335052876962259

In [ ]:
study.trials_dataframe().head()

,number,value,datetime_start,datetime_complete,duration,params_bootstrap,params_max_depth,params_max_features,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,3.072966,2026-07-02 00:31:21.152154,2026-07-02 00:36:31.759174,0 days 00:05:10.607020,False,18,0.575202,17,17,165,COMPLETE
1,1,3.061151,2026-07-02 00:31:21.153494,2026-07-02 00:33:39.105108,0 days 00:02:17.951614,True,14,0.547723,8,20,253,COMPLETE
2,2,3.076381,2026-07-02 00:31:21.154531,2026-07-02 00:33:56.550174,0 days 00:02:35.395643,False,28,0.592388,20,16,242,COMPLETE
3,3,3.072054,2026-07-02 00:31:21.155375,2026-07-02 00:38:47.102166,0 days 00:07:25.946791,True,25,0.756241,11,13,201,COMPLETE
4,4,3.071098,2026-07-02 00:31:21.156738,2026-07-02 00:36:46.851322,0 days 00:05:25.694584,True,30,0.293992,6,14,147,COMPLETE

In [ ]:
plot_optimization_history(study)

In [ ]:
plot_param_importances(study)

In [ ]:
plot_slice(study)

In [ ]:
plot_parallel_coordinate(study)