In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV , KFold , cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
from sklearn.compose import ColumnTransformer , TransformedTargetRegressor
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder , PowerTransformer
from sklearn.base import BaseEstimator , TransformerMixin
import optuna
from lightgbm import LGBMRegressor
import mlflow
import dagshub
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_parallel_coordinate , plot_slice

In [2]:
dagshub.init(repo_owner="mridul0010" , repo_name="food-delivery-time-prediction" , mlflow=True)

Accessing as mridul0010

Initialized MLflow to track repo "mridul0010/food-delivery-time-prediction"

Repository mridul0010/food-delivery-time-prediction initialized!

In [3]:
mlflow.set_tracking_uri("https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow")

In [4]:
mlflow.set_experiment("3. Hyperparameter Tuning - RF")

2026/07/05 16:23:14 INFO mlflow.tracking.fluent: Experiment with name '3. Hyperparameter Tuning - RF' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/4e0f39779d504c019a0c189197867755', creation_time=1783248795597, effective_trace_archival_retention=None, experiment_id='3', last_update_time=1783248795597, lifecycle_stage='active', name='3. Hyperparameter Tuning - RF', tags={}, trace_location=None, workspace='default'>

In [5]:
df = pd.read_csv('../data/Cleaned Delivery Dataset.csv')

In [6]:
pd.set_option('display.max_columns' , None)

In [7]:
df.drop(columns=['Delivery_Agent'] , inplace=True)

In [8]:
df['Order_Datetime'] = pd.to_datetime(df['Order_Datetime'])
df['Pickup_Datetime'] = pd.to_datetime(df['Pickup_Datetime'])

In [9]:
class FeatureEngineering(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.rating_bins = None

    def fit(self, X, y=None):
        X = X.copy()
        
        # Store bins for consistent transformation
        self.rating_bins = pd.qcut(
            X['Delivery_person_Ratings'],
            q=3,
            retbins=True,
            duplicates='drop'
        )[1]
        
        return self

    def transform(self, X):
        X = X.copy()

        # Datetime conversion
        X['Order_Datetime'] = pd.to_datetime(X['Order_Datetime'], errors='coerce')
        X['Pickup_Datetime'] = pd.to_datetime(X['Pickup_Datetime'], errors='coerce')

        # Rating group
        X["delivery_rating_group"] = pd.cut(
            X['Delivery_person_Ratings'],
            bins=self.rating_bins,
            labels=['Low', 'Medium', 'High'],
            include_lowest=True
        )

        # Age group
        X["age_group"] = pd.cut(
            X['Delivery_person_Age'],
            bins=[14, 25, 35, 60],
            labels=['Young', 'Adult', 'Senior']
        )

        # Distance group
        X["distance_group"] = pd.cut(
            X['distance_km'],
            bins=[0, 5, 10, 25],
            labels=['Short Distance', 'Medium Distance', 'Long Distance']
        )

        # Time features
        X['Prep_Time(min)'] = (
            X['Pickup_Datetime'] - X['Order_Datetime']
        ).dt.total_seconds() / 60

        X['Order_hour'] = X['Order_Datetime'].dt.hour
        X['Order_day'] = X['Order_Datetime'].dt.day_name()

        X['isWeekend'] = X['Order_day'].isin(["Saturday", "Sunday"]).astype(int)

        X['Time_Of_Day'] = pd.cut(
            X['Order_hour'],
            bins=[0, 6, 12, 18, 24],
            labels=["Night", "Morning", "Afternoon", "Evening"],
            include_lowest=True
        )

        # Drop raw datetime
        X = X.drop(columns=['Order_Datetime', 'Pickup_Datetime'], errors='ignore')

        return X

    def get_feature_names_out(self , input_features = None):
        return input_features

In [10]:
X = df.drop(columns=['Time_taken (min)'])
y = df['Time_taken (min)']

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [12]:
X

,City,Zone,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,distance_km,Order_Datetime,Pickup_Datetime,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type
0,Dehradun,Zone17,36,4.2,30.327968,78.046106,30.397968,78.116106,10.28,2022-12-02 21:55:00,2022-12-02 22:10:00,Fog,Jam,Good,Snack,motorcycle,3,No,Metropolitian
1,Kochi,Zone16,21,4.7,10.003064,76.307589,10.043064,76.347589,6.24,2022-02-13 14:55:00,2022-02-13 15:05:00,Stormy,High,Average,Meal,motorcycle,1,No,Metropolitian
2,Pune,Zone13,23,4.7,18.562450,73.916619,18.652450,74.006619,13.79,2022-04-03 17:30:00,2022-04-03 17:40:00,Sandstorms,Medium,Average,Drinks,scooter,1,No,Metropolitian
3,Ludhiana,Zone15,34,4.3,30.899584,75.809346,30.919584,75.829346,2.93,2022-02-13 09:20:00,2022-02-13 09:30:00,Sandstorms,Low,poor,Buffet,motorcycle,0,No,Metropolitian
4,Kanpur,Zone14,24,4.7,26.463504,80.372929,26.593504,80.502929,19.40,2022-02-14 19:50:00,2022-02-14 20:05:00,Fog,Jam,Average,Snack,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39637,Bangalore,Zone16,28,4.9,13.029198,77.570997,13.059198,77.600997,4.66,2022-03-30 21:55:00,2022-03-30 22:05:00,Sandstorms,Jam,Average,Meal,scooter,1,No,Metropolitian
39638,Ranchi,Zone16,35,4.2,23.371292,85.327872,23.481292,85.437872,16.60,2022-08-03 21:45:00,2022-08-03 21:55:00,Windy,Jam,Good,Drinks,motorcycle,1,No,Metropolitian
39639,Chennai,Zone08,30,4.9,13.022394,80.242439,13.052394,80.272439,4.66,2022-11-03 23:50:00,2022-11-04 00:05:00,Cloudy,Low,Average,Drinks,scooter,0,No,Metropolitian
39640,Coimbatore,Zone11,20,4.7,11.001753,76.986241,11.041753,77.026241,6.23,2022-07-03 13:35:00,2022-07-03 13:40:00,Cloudy,High,poor,Snack,motorcycle,1,No,Metropolitian
39641,Ranchi,Zone09,23,4.9,23.351058,85.325731,23.431058,85.405731,12.07,2022-02-03 17:10:00,2022-02-03 17:15:00,Fog,Medium,Good,Snack,scooter,1,No,Metropolitian

In [13]:
numerical = ['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 
       'multiple_deliveries', 'distance_km', 'Prep_Time(min)', 'Order_hour',
       'isWeekend']

ohe_col = ['City', 'Zone', 'Weather_conditions',
       'Type_of_order', 'Type_of_vehicle',
       'City_Type','Order_day', 'Time_Of_Day']

ordinal_col = ['Road_traffic_density' , 'Vehicle_condition' , 'Festival',
       'delivery_rating_group' , 'age_group' , 'distance_group']

In [14]:
Road_traffic_density = ['Low', 'Medium', 'High', 'Jam']
Vehicle_condition = ['poor', 'Average', 'Good' , 'Excellent']
Festival = ['No', 'Yes']
delivery_rating_group = ['Low', 'Medium', 'High']
age_group = ['Young', 'Adult', 'Senior']         
distance_group = ['Short Distance', 'Medium Distance', 'Long Distance']

In [15]:
transformer = ColumnTransformer(
    transformers=[
        ("ohe" , OneHotEncoder(sparse_output=False , handle_unknown='ignore') , ohe_col),
        ('oe' , OrdinalEncoder(categories=[
            Road_traffic_density , Vehicle_condition,
            Festival , delivery_rating_group,
            age_group , distance_group
        ]) , ordinal_col),
        ('Scaling' , StandardScaler() , numerical)
    ],remainder='passthrough'
)

In [16]:
pipeline = Pipeline(
    [
        ("FeatureEngineering" , FeatureEngineering()),
        ("ColumnTransformer" , transformer)
    ]
)

In [17]:
X_train_trans = pipeline.fit_transform(X_train)
X_test_trans = pipeline.transform(X_test)

In [18]:
pt = PowerTransformer()

In [19]:
def objective(trial):
    with mlflow.start_run(nested=True):
        params = {
            # Number of trees in the forest
            "n_estimators": trial.suggest_int("n_estimators", 50, 300),
            
            # Maximum depth of the tree
            "max_depth": trial.suggest_int("max_depth", 2, 32),
            
            # Minimum number of samples required to split an internal node
            "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
            
            # Minimum number of samples required to be at a leaf node
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20),
            
            # Number of features to consider when looking for the best split
            "max_features": trial.suggest_float("max_features", 0.1, 1.0),
            
            # Whether bootstrap samples are used when building trees
            "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
            
            "random_state": 42,
            "n_jobs": -1,
        }

        # log params
        mlflow.log_params(params)


        rf = RandomForestRegressor(**params)
        model = TransformedTargetRegressor(regressor=rf , transformer=pt)

        model.fit(X_train_trans , y_train)

        cv_score = cross_val_score(
            model ,
            X_train_trans , 
            y_train , 
            cv=10 , 
            scoring="neg_mean_absolute_error",
            n_jobs=-1
        )

        mean_score = -(cv_score.mean())

        # log avg cross val error
        mlflow.log_metric("cross_val_error" , mean_score)

        return mean_score

In [20]:
study = optuna.create_study(direction='minimize')

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective , n_trials=50 , n_jobs=-1 , show_progress_bar=True)

    # log the best params
    mlflow.log_params(study.best_params)

    # log best score
    mlflow.log_metric("best_score" , study.best_value)

    # training the lgbm on best param
    best_rf = RandomForestRegressor(**study.best_params)

    best_model = TransformedTargetRegressor(regressor=best_rf , transformer=pt)

    best_model.fit(X_train_trans , y_train)

    y_pred_train = best_model.predict(X_train_trans)
    y_pred_test = best_model.predict(X_test_trans)

    scores = cross_val_score(
        best_model,
        X_train_trans,
        y_train,
        scoring="neg_mean_absolute_error",
        cv=5,n_jobs=-1
    )

    # logging metrics
    mlflow.log_metric("Training_error" ,mean_absolute_error(y_train ,y_pred_train))
    mlflow.log_metric("Test_error" ,mean_absolute_error(y_test ,y_pred_test))
    mlflow.log_metric("Training_r2" ,r2_score(y_train ,y_pred_train))
    mlflow.log_metric("Test_r2" ,r2_score(y_test ,y_pred_test))
    mlflow.log_metric("cross_val" , -scores.mean())

    # Generate the optuna plots
    fig_history = plot_optimization_history(study)
    fig_parallel = plot_parallel_coordinate(study)
    fig_importance = plot_param_importances(study)
    fig_slice = plot_slice(study)

    # Loginf plots
    mlflow.log_figure(fig_history, "optuna_plots/optimization_history.html")
    mlflow.log_figure(fig_importance, "optuna_plots/param_importances.html")
    mlflow.log_figure(fig_parallel, "optuna_plots/parallel_coordinate.html")
    mlflow.log_figure(fig_slice, "optuna_plots/plot_slice.html")
    
    # log the best model 
    mlflow.sklearn.log_model(best_rf , artifact_path="model_RF")

[I 2026-07-05 16:23:15,330] A new study created in memory with name: no-name-3450cc49-da9e-4ba3-8673-0a7e55646cb1
  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run bold-wolf-30 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/086e12d6b2e943c7bedbd25d8bcdaa01
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 6. Best value: 3.6067:   2%|▏         | 1/50 [01:11<58:11, 71.25s/it]

[I 2026-07-05 16:24:27,210] Trial 6 finished with value: 3.606703111945367 and parameters: {'n_estimators': 154, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 18, 'max_features': 0.3556766665934924, 'bootstrap': False}. Best is trial 6 with value: 3.606703111945367.
🏃 View run caring-swan-228 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/987a608e01d543fcb5b40508bf69c718
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 3. Best value: 3.13539:   4%|▍         | 2/50 [01:30<32:25, 40.53s/it]

[I 2026-07-05 16:24:46,241] Trial 3 finished with value: 3.1353855799042067 and parameters: {'n_estimators': 84, 'max_depth': 24, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 0.6990614168921144, 'bootstrap': False}. Best is trial 3 with value: 3.1353855799042067.
🏃 View run righteous-ant-483 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/a903861ca39b468bac2ea27c1c22fedc
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 4. Best value: 3.07677:   6%|▌         | 3/50 [03:27<59:19, 75.72s/it]

[I 2026-07-05 16:26:43,842] Trial 4 finished with value: 3.076766155536161 and parameters: {'n_estimators': 102, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5509940136470908, 'bootstrap': True}. Best is trial 4 with value: 3.076766155536161.
🏃 View run polite-lamb-329 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/776f8f2a73f3466484a6601d39904c77
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3
🏃 View run adorable-mule-978 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/2cf5d0472d9547638d7527ef364c7b36
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 7. Best value: 3.06327:   8%|▊         | 4/50 [03:50<42:00, 54.80s/it]

[I 2026-07-05 16:27:06,426] Trial 7 finished with value: 3.0632732377108987 and parameters: {'n_estimators': 127, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.2011269563785641, 'bootstrap': False}. Best is trial 7 with value: 3.0632732377108987.
🏃 View run gregarious-seal-490 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/bd0e5214685b440dbde359bf3977b089
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 7. Best value: 3.06327:  10%|█         | 5/50 [04:04<30:07, 40.17s/it]

[I 2026-07-05 16:27:20,800] Trial 15 finished with value: 3.089431444441483 and parameters: {'n_estimators': 210, 'max_depth': 26, 'min_samples_split': 16, 'min_samples_leaf': 19, 'max_features': 0.7935930491212223, 'bootstrap': True}. Best is trial 7 with value: 3.0632732377108987.
🏃 View run luxuriant-roo-99 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/ea693a4c849045ee9548b3ce44f3e8f2
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 7. Best value: 3.06327:  12%|█▏        | 6/50 [04:21<23:38, 32.23s/it]

[I 2026-07-05 16:27:37,534] Trial 1 finished with value: 3.0747619816007754 and parameters: {'n_estimators': 132, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.4496422624251575, 'bootstrap': False}. Best is trial 7 with value: 3.0632732377108987.
🏃 View run marvelous-lamb-543 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/2eb9b357d5da4d7b8b084aac48d21933
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 7. Best value: 3.06327:  14%|█▍        | 7/50 [04:31<17:45, 24.77s/it]

[I 2026-07-05 16:27:46,879] Trial 12 finished with value: 3.1501766428781837 and parameters: {'n_estimators': 66, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 15, 'max_features': 0.8622835923222569, 'bootstrap': False}. Best is trial 7 with value: 3.0632732377108987.
🏃 View run popular-crab-818 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/0ba2bb82677d4a06871d8a9b54f59a6b
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  16%|█▌        | 8/50 [04:41<14:04, 20.12s/it]

[I 2026-07-05 16:27:57,184] Trial 0 finished with value: 3.0514108256098917 and parameters: {'n_estimators': 206, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 0.39470578430460934, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run suave-cat-665 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/f209c51c45ca4a039e209a39e607cb31
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  18%|█▊        | 9/50 [04:49<11:06, 16.26s/it]

[I 2026-07-05 16:28:04,974] Trial 8 finished with value: 3.760599774005737 and parameters: {'n_estimators': 125, 'max_depth': 6, 'min_samples_split': 18, 'min_samples_leaf': 1, 'max_features': 0.47757776553421893, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.

Best trial: 0. Best value: 3.05141:  20%|██        | 10/50 [04:54<08:43, 13.09s/it]

[I 2026-07-05 16:28:10,949] Trial 10 finished with value: 3.880588831307185 and parameters: {'n_estimators': 82, 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 0.15668031599997273, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run judicious-ant-506 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/a15e6157ef71489bbeb2c38c852bc1ec
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  20%|██        | 10/50 [05:03<08:43, 13.09s/it]

[I 2026-07-05 16:28:19,703] Trial 11 finished with value: 3.0876575984117243 and parameters: {'n_estimators': 210, 'max_depth': 18, 'min_samples_split': 20, 'min_samples_leaf': 18, 'max_features': 0.6999844060973028, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.

Best trial: 0. Best value: 3.05141:  22%|██▏       | 11/50 [05:04<07:44, 11.90s/it]

🏃 View run powerful-hog-469 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/eab76e36f59d4afcb48c76b85f961d13
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  24%|██▍       | 12/50 [05:46<13:19, 21.03s/it]

[I 2026-07-05 16:29:02,081] Trial 13 finished with value: 3.110588741540161 and parameters: {'n_estimators': 214, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 0.6319263258738094, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run mysterious-snipe-893 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/374bb89027a743e49cbf10769d029240
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  26%|██▌       | 13/50 [05:50<09:52, 16.02s/it]

[I 2026-07-05 16:29:06,571] Trial 14 finished with value: 5.183408252314981 and parameters: {'n_estimators': 107, 'max_depth': 3, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.9896864684788304, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run vaunted-flea-46 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/63861db8055442209c7d6d00d1b79631
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  28%|██▊       | 14/50 [06:48<17:14, 28.72s/it]

[I 2026-07-05 16:30:04,647] Trial 9 finished with value: 3.0523916595798064 and parameters: {'n_estimators': 211, 'max_depth': 32, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 0.3961338627635732, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run masked-midge-982 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/c64e1de896eb44fea70e69cd7d97d7b1
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  30%|███       | 15/50 [07:58<24:02, 41.20s/it]

[I 2026-07-05 16:31:14,763] Trial 5 finished with value: 3.3536304699491843 and parameters: {'n_estimators': 164, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 0.9937042360270913, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run resilient-snail-691 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/a077693dc0fd4e2baeaefcf9846e16ff
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  32%|███▏      | 16/50 [08:02<17:01, 30.05s/it]

[I 2026-07-05 16:31:18,922] Trial 2 finished with value: 3.0571813413743647 and parameters: {'n_estimators': 257, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 0.27360566490317056, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run intrigued-snipe-340 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/b97a8c96bb67471788ac1920df78e6a9
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  34%|███▍      | 17/50 [08:15<13:34, 24.68s/it]

[I 2026-07-05 16:31:31,092] Trial 17 finished with value: 3.5803433472425192 and parameters: {'n_estimators': 207, 'max_depth': 8, 'min_samples_split': 12, 'min_samples_leaf': 15, 'max_features': 0.2413335045085355, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run unleashed-dove-169 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/6f3d17709fcc44d588f4245eacf6120c
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  36%|███▌      | 18/50 [09:29<21:04, 39.53s/it]

[I 2026-07-05 16:32:45,205] Trial 18 finished with value: 3.7546304692555905 and parameters: {'n_estimators': 206, 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 16, 'max_features': 0.47358120796253234, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run serious-mare-48 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/44b1545bcf3746c18384f1f97ccc63a4
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  38%|███▊      | 19/50 [09:31<14:37, 28.31s/it]

[I 2026-07-05 16:32:47,374] Trial 16 finished with value: 3.114734779618142 and parameters: {'n_estimators': 178, 'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 0.7659296058850358, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run clean-squid-391 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/1dd3d945dbd546c4a84fa7544224cdab
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  40%|████      | 20/50 [09:40<11:16, 22.56s/it]

[I 2026-07-05 16:32:56,528] Trial 22 finished with value: 4.402382247335038 and parameters: {'n_estimators': 82, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 18, 'max_features': 0.2421488178832643, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run hilarious-kite-250 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/beafac3c5b89496587641a2c0471e433
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  42%|████▏     | 21/50 [09:52<09:19, 19.29s/it]

[I 2026-07-05 16:33:08,205] Trial 21 finished with value: 4.77267387173837 and parameters: {'n_estimators': 289, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 16, 'max_features': 0.14204066231471332, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run serious-auk-245 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/7b90a25a8ac84879af3036577fe85b22
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  44%|████▍     | 22/50 [10:14<09:29, 20.33s/it]

[I 2026-07-05 16:33:30,953] Trial 20 finished with value: 3.0930235533031305 and parameters: {'n_estimators': 208, 'max_depth': 21, 'min_samples_split': 15, 'min_samples_leaf': 15, 'max_features': 0.3628836328867363, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run colorful-cod-266 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/0ff0d9ac6aac4d97aee9a59882111015
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  46%|████▌     | 23/50 [10:29<08:21, 18.58s/it]

[I 2026-07-05 16:33:45,448] Trial 24 finished with value: 3.053804339263588 and parameters: {'n_estimators': 84, 'max_depth': 18, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': 0.32063612399722496, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run handsome-fish-154 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/0d8931cc205a4cab840ba7f4b33b54c9
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  48%|████▊     | 24/50 [10:58<09:23, 21.66s/it]

[I 2026-07-05 16:34:14,288] Trial 23 finished with value: 3.1097786063353574 and parameters: {'n_estimators': 287, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 15, 'max_features': 0.22322374722677696, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run placid-wasp-349 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/f6734316c344455b8ba4278e8f110e47
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  50%|█████     | 25/50 [11:35<10:57, 26.30s/it]

[I 2026-07-05 16:34:51,403] Trial 26 finished with value: 3.210160877947825 and parameters: {'n_estimators': 292, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 0.14483462265565744, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run dazzling-doe-157 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/e234ad3e6b3846b4948a04539a9e8e1c
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  52%|█████▏    | 26/50 [13:05<18:07, 45.30s/it]

[I 2026-07-05 16:36:21,037] Trial 19 finished with value: 3.2036670636273166 and parameters: {'n_estimators': 156, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 0.7777347153801967, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run gifted-cat-661 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/5a04a97d10974e3ea38e102c0a26a3ee
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  54%|█████▍    | 27/50 [16:01<32:25, 84.60s/it]

[I 2026-07-05 16:39:17,339] Trial 27 finished with value: 3.140327552620816 and parameters: {'n_estimators': 284, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 11, 'max_features': 0.17257742757492667, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run resilient-pig-30 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/16a1d85d31af4c0c8408b61f015d6dc0
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  56%|█████▌    | 28/50 [16:02<21:49, 59.54s/it]

[I 2026-07-05 16:39:18,416] Trial 28 finished with value: 3.097271491280144 and parameters: {'n_estimators': 300, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.198802231009412, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run gregarious-stag-33 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/3523dd784f724f0e89a5a1f6fb4142da
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  58%|█████▊    | 29/50 [17:10<21:45, 62.17s/it]

[I 2026-07-05 16:40:26,707] Trial 25 finished with value: 3.0762216792803287 and parameters: {'n_estimators': 294, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 0.9863002688502873, 'bootstrap': True}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run amusing-conch-812 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/6ed62576e61e4460bfc316ddf2e99956
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  60%|██████    | 30/50 [17:45<18:00, 54.03s/it]

[I 2026-07-05 16:41:01,740] Trial 29 finished with value: 3.054459184096735 and parameters: {'n_estimators': 286, 'max_depth': 31, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 0.3058697860017806, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run rare-zebra-741 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/520100a123854caeb5166d21ee4929bc
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  62%|██████▏   | 31/50 [18:03<13:37, 43.02s/it]

[I 2026-07-05 16:41:19,078] Trial 30 finished with value: 3.0559705075712102 and parameters: {'n_estimators': 294, 'max_depth': 32, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 0.2941182233154395, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run omniscient-elk-904 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/704791afdf79407bbb3b7cb107f5ff40
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  64%|██████▍   | 32/50 [19:06<14:45, 49.19s/it]

[I 2026-07-05 16:42:22,654] Trial 31 finished with value: 3.0528429490527365 and parameters: {'n_estimators': 299, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 11, 'max_features': 0.36924954624254014, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run respected-gull-291 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/1d44a394029c4bddaf9c18db75fbd7d8
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  66%|██████▌   | 33/50 [20:10<15:12, 53.67s/it]

[I 2026-07-05 16:43:26,772] Trial 32 finished with value: 3.051942641579938 and parameters: {'n_estimators': 300, 'max_depth': 31, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.40479786864898243, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run bittersweet-ape-938 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/0fb2b527ab0843c6b0ecf13037100909
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 0. Best value: 3.05141:  68%|██████▊   | 34/50 [20:16<10:29, 39.33s/it]

[I 2026-07-05 16:43:32,625] Trial 34 finished with value: 3.0522775290704893 and parameters: {'n_estimators': 281, 'max_depth': 32, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 0.3314635834843819, 'bootstrap': False}. Best is trial 0 with value: 3.0514108256098917.
🏃 View run youthful-rat-182 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/691d8a07fbf242bc9a4a99aa58ea83b3
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 33. Best value: 3.05096:  70%|███████   | 35/50 [21:38<13:02, 52.20s/it]

[I 2026-07-05 16:44:54,873] Trial 33 finished with value: 3.050962077646925 and parameters: {'n_estimators': 283, 'max_depth': 32, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 0.33478594258324035, 'bootstrap': False}. Best is trial 33 with value: 3.050962077646925.
🏃 View run agreeable-trout-173 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/9bd8f18f067f423aa7e501aebd76c333
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 35. Best value: 3.05075:  72%|███████▏  | 36/50 [22:10<10:44, 46.00s/it]

[I 2026-07-05 16:45:26,426] Trial 35 finished with value: 3.0507541239958287 and parameters: {'n_estimators': 288, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 0.3587628238772381, 'bootstrap': False}. Best is trial 35 with value: 3.0507541239958287.
🏃 View run sassy-goose-699 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/6afd35a3d7564561a0c72ffdc85c61fe
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 35. Best value: 3.05075:  74%|███████▍  | 37/50 [22:33<08:29, 39.17s/it]

[I 2026-07-05 16:45:49,655] Trial 36 finished with value: 3.050865685732075 and parameters: {'n_estimators': 254, 'max_depth': 31, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 0.3277912701861871, 'bootstrap': False}. Best is trial 35 with value: 3.0507541239958287.
🏃 View run salty-finch-114 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/8d6de3c62a39457abd45da1b67f751ce
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 37. Best value: 3.05073:  76%|███████▌  | 38/50 [23:18<08:11, 41.00s/it]

[I 2026-07-05 16:46:34,921] Trial 37 finished with value: 3.050729072103135 and parameters: {'n_estimators': 261, 'max_depth': 32, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 0.32701251295042943, 'bootstrap': False}. Best is trial 37 with value: 3.050729072103135.
🏃 View run stately-kit-979 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/580b33eb15f54603bf7733ef0986c3e9
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  78%|███████▊  | 39/50 [23:30<05:55, 32.29s/it]

[I 2026-07-05 16:46:46,890] Trial 38 finished with value: 3.0503467002445985 and parameters: {'n_estimators': 243, 'max_depth': 31, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 0.3572862510877454, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run debonair-kit-674 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/f355d4d9eec44a408b86f6d3c3b87ca3
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  80%|████████  | 40/50 [24:13<05:53, 35.33s/it]

[I 2026-07-05 16:47:29,314] Trial 39 finished with value: 3.051677919848111 and parameters: {'n_estimators': 246, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 0.3349817164097888, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run dazzling-perch-473 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/88f38e05eed347fd90b36cf19cc6e6a9
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  82%|████████▏ | 41/50 [24:59<05:47, 38.61s/it]

[I 2026-07-05 16:48:15,558] Trial 40 finished with value: 3.05146337032957 and parameters: {'n_estimators': 248, 'max_depth': 31, 'min_samples_split': 5, 'min_samples_leaf': 11, 'max_features': 0.3475404141335881, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run rumbling-hawk-92 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/d43c96aa65a74f21885d61870195fd9e
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  84%|████████▍ | 42/50 [25:07<03:54, 29.37s/it]

[I 2026-07-05 16:48:23,377] Trial 41 finished with value: 3.0545687011244675 and parameters: {'n_estimators': 247, 'max_depth': 31, 'min_samples_split': 5, 'min_samples_leaf': 11, 'max_features': 0.3445396163880299, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run kindly-calf-242 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/0a6e14c5c2f74a198ea130a067d56742
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  86%|████████▌ | 43/50 [25:49<03:52, 33.28s/it]

[I 2026-07-05 16:49:05,793] Trial 42 finished with value: 3.054551578794404 and parameters: {'n_estimators': 246, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 11, 'max_features': 0.33505204278583633, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run mysterious-croc-603 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/cd3ac17fdadf4113b61b71569fb5f6d9
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  88%|████████▊ | 44/50 [26:34<03:39, 36.58s/it]

[I 2026-07-05 16:49:50,057] Trial 43 finished with value: 3.050767355121446 and parameters: {'n_estimators': 245, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.36318121776321577, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run angry-robin-786 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/d28dcfa5d6834406b46cb2b090b381fa
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  90%|█████████ | 45/50 [27:09<03:01, 36.34s/it]

[I 2026-07-05 16:50:25,859] Trial 44 finished with value: 3.0535245717816393 and parameters: {'n_estimators': 239, 'max_depth': 31, 'min_samples_split': 9, 'min_samples_leaf': 12, 'max_features': 0.35495682697377823, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run righteous-gnat-29 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/f0481c4a67784c7ba523d7e9b66cdedd
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  92%|█████████▏| 46/50 [27:33<02:10, 32.53s/it]

[I 2026-07-05 16:50:49,473] Trial 45 finished with value: 3.0572937606418646 and parameters: {'n_estimators': 236, 'max_depth': 32, 'min_samples_split': 9, 'min_samples_leaf': 12, 'max_features': 0.40931312961063826, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run vaunted-lark-774 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/1018aab4518642a797cad9201bccf994
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  94%|█████████▍| 47/50 [28:13<01:44, 34.91s/it]

[I 2026-07-05 16:51:29,947] Trial 46 finished with value: 3.0520349756227643 and parameters: {'n_estimators': 249, 'max_depth': 32, 'min_samples_split': 9, 'min_samples_leaf': 12, 'max_features': 0.38365855152443573, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run righteous-stork-734 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/3d6bc640a3cb48ff8b1e068d8c40360a
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  96%|█████████▌| 48/50 [29:06<01:20, 40.28s/it]

[I 2026-07-05 16:52:22,767] Trial 47 finished with value: 3.0526287431960677 and parameters: {'n_estimators': 246, 'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': 0.3975307932285953, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run classy-fowl-541 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/e6c0ac055c7443c68f0212ff96b1b8d0
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035:  98%|█████████▊| 49/50 [29:30<00:35, 35.40s/it]

[I 2026-07-05 16:52:46,770] Trial 48 finished with value: 3.0555846918841807 and parameters: {'n_estimators': 256, 'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 12, 'max_features': 0.42219339612690393, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.
🏃 View run spiffy-lark-735 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/40da8fbe1ba145aaaac12ecbae3fb3d7
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

Best trial: 38. Best value: 3.05035: 100%|██████████| 50/50 [30:12<00:00, 36.24s/it]

[I 2026-07-05 16:53:28,156] Trial 49 finished with value: 3.075094962973542 and parameters: {'n_estimators': 252, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 0.5520342782566912, 'bootstrap': False}. Best is trial 38 with value: 3.0503467002445985.

2026/07/05 16:54:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/05 16:55:00 WARNING mlflow.utils.requirements_utils: Found torch version (2.12.1+cu130) contains a local version label (+cu130). MLflow logged a pip requirement for this package as 'torch==2.12.1' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

🏃 View run best_model at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3/runs/ceea48a6eadf4eeeb02760bc66757384
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/3

In [21]:
study.best_value

3.0503467002445985

In [22]:
study.best_params

{'n_estimators': 243,
 'max_depth': 31,
 'min_samples_split': 5,
 'min_samples_leaf': 10,
 'max_features': 0.3572862510877454,
 'bootstrap': False}

In [23]:
best_rf = RandomForestRegressor(**study.best_params)

model = TransformedTargetRegressor(regressor=best_rf , transformer=pt)

model.fit(X_train_trans , y_train)

TransformedTargetRegressor(regressor=RandomForestRegressor(bootstrap=False,
                                                           max_depth=31,
                                                           max_features=0.3572862510877454,
                                                           min_samples_leaf=10,
                                                           min_samples_split=5,
                                                           n_estimators=243),
                           transformer=PowerTransformer())

In [24]:
y_pred = model.predict(X_test_trans)

r2_score(y_test , y_pred)

0.8285720894894504

In [25]:
study.trials_dataframe().head()

,number,value,datetime_start,datetime_complete,duration,params_bootstrap,params_max_depth,params_max_features,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,3.051411,2026-07-05 16:23:15.966034,2026-07-05 16:27:57.184811,0 days 00:04:41.218777,False,21,0.394706,8,5,206,COMPLETE
1,1,3.074762,2026-07-05 16:23:15.966640,2026-07-05 16:27:37.534427,0 days 00:04:21.567787,False,28,0.449642,4,10,132,COMPLETE
2,2,3.057181,2026-07-05 16:23:15.967470,2026-07-05 16:31:18.922358,0 days 00:08:02.954888,False,14,0.273606,6,10,257,COMPLETE
3,3,3.135386,2026-07-05 16:23:15.968560,2026-07-05 16:24:46.241324,0 days 00:01:30.272764,False,24,0.699061,1,20,84,COMPLETE
4,4,3.076766,2026-07-05 16:23:15.969312,2026-07-05 16:26:43.842820,0 days 00:03:27.873508,True,11,0.550994,4,2,102,COMPLETE

In [26]:
plot_optimization_history(study)

In [27]:
plot_param_importances(study)

In [28]:
plot_slice(study)

In [29]:
plot_parallel_coordinate(study)