In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV , KFold , cross_val_score
from sklearn.linear_model import LinearRegression 
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
from sklearn.compose import ColumnTransformer , TransformedTargetRegressor
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder , PowerTransformer
from sklearn.base import BaseEstimator , TransformerMixin
import optuna
from lightgbm import LGBMRegressor
import mlflow
import dagshub
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_parallel_coordinate , plot_slice

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dagshub.init(repo_owner="mridul0010" , repo_name="Delivery-Time-Analysis-Prediction" , mlflow=True)

Accessing as mridul0010

Initialized MLflow to track repo "mridul0010/Delivery-Time-Analysis-Prediction"

Repository mridul0010/Delivery-Time-Analysis-Prediction initialized!

In [3]:
mlflow.set_tracking_uri("https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow")

In [4]:
mlflow.set_experiment("Model Selection")

2026/07/01 22:40:18 INFO mlflow.tracking.fluent: Experiment with name 'Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/1f45928a57534e5e9119d535a3d497a7', creation_time=1782925820593, effective_trace_archival_retention=None, experiment_id='5', last_update_time=1782925820593, lifecycle_stage='active', name='Model Selection', tags={}, trace_location=None, workspace='default'>

In [ ]:
df = pd.read_csv('../data/Cleaned Delivery Dataset.csv')

In [6]:
pd.set_option('display.max_columns' , None)

In [7]:
df.drop(columns=['Delivery_Agent'] , inplace=True)

In [8]:
df['Order_Datetime'] = pd.to_datetime(df['Order_Datetime'])
df['Pickup_Datetime'] = pd.to_datetime(df['Pickup_Datetime'])

In [9]:
class FeatureEngineering(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.rating_bins = None

    def fit(self, X, y=None):
        X = X.copy()
        
        # Store bins for consistent transformation
        self.rating_bins = pd.qcut(
            X['Delivery_person_Ratings'],
            q=3,
            retbins=True,
            duplicates='drop'
        )[1]
        
        return self

    def transform(self, X):
        X = X.copy()

        # Datetime conversion
        X['Order_Datetime'] = pd.to_datetime(X['Order_Datetime'], errors='coerce')
        X['Pickup_Datetime'] = pd.to_datetime(X['Pickup_Datetime'], errors='coerce')

        # Rating group
        X["delivery_rating_group"] = pd.cut(
            X['Delivery_person_Ratings'],
            bins=self.rating_bins,
            labels=['Low', 'Medium', 'High'],
            include_lowest=True
        )

        # Age group
        X["age_group"] = pd.cut(
            X['Delivery_person_Age'],
            bins=[14, 25, 35, 60],
            labels=['Young', 'Adult', 'Senior']
        )

        # Distance group
        X["distance_group"] = pd.cut(
            X['distance_km'],
            bins=[0, 5, 10, 25],
            labels=['Short Distance', 'Medium Distance', 'Long Distance']
        )

        # Time features
        X['Prep_Time(min)'] = (
            X['Pickup_Datetime'] - X['Order_Datetime']
        ).dt.total_seconds() / 60

        X['Order_hour'] = X['Order_Datetime'].dt.hour
        X['Order_day'] = X['Order_Datetime'].dt.day_name()

        X['isWeekend'] = X['Order_day'].isin(["Saturday", "Sunday"]).astype(int)

        X['Time_Of_Day'] = pd.cut(
            X['Order_hour'],
            bins=[0, 6, 12, 18, 24],
            labels=["Night", "Morning", "Afternoon", "Evening"],
            include_lowest=True
        )

        # Drop raw datetime
        X = X.drop(columns=['Order_Datetime', 'Pickup_Datetime'], errors='ignore')

        return X

    def get_feature_names_out(self , input_features = None):
        return input_features

In [10]:
X = df.drop(columns=['Time_taken (min)'])
y = df['Time_taken (min)']

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [12]:
X

,City,Zone,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,distance_km,Order_Datetime,Pickup_Datetime,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type
0,Dehradun,Zone17,36,4.2,30.327968,78.046106,30.397968,78.116106,10.28,2022-12-02 21:55:00,2022-12-02 22:10:00,Fog,Jam,Good,Snack,motorcycle,3,No,Metropolitian
1,Kochi,Zone16,21,4.7,10.003064,76.307589,10.043064,76.347589,6.24,2022-02-13 14:55:00,2022-02-13 15:05:00,Stormy,High,Average,Meal,motorcycle,1,No,Metropolitian
2,Pune,Zone13,23,4.7,18.562450,73.916619,18.652450,74.006619,13.79,2022-04-03 17:30:00,2022-04-03 17:40:00,Sandstorms,Medium,Average,Drinks,scooter,1,No,Metropolitian
3,Ludhiana,Zone15,34,4.3,30.899584,75.809346,30.919584,75.829346,2.93,2022-02-13 09:20:00,2022-02-13 09:30:00,Sandstorms,Low,poor,Buffet,motorcycle,0,No,Metropolitian
4,Kanpur,Zone14,24,4.7,26.463504,80.372929,26.593504,80.502929,19.40,2022-02-14 19:50:00,2022-02-14 20:05:00,Fog,Jam,Average,Snack,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39637,Bangalore,Zone16,28,4.9,13.029198,77.570997,13.059198,77.600997,4.66,2022-03-30 21:55:00,2022-03-30 22:05:00,Sandstorms,Jam,Average,Meal,scooter,1,No,Metropolitian
39638,Ranchi,Zone16,35,4.2,23.371292,85.327872,23.481292,85.437872,16.60,2022-08-03 21:45:00,2022-08-03 21:55:00,Windy,Jam,Good,Drinks,motorcycle,1,No,Metropolitian
39639,Chennai,Zone08,30,4.9,13.022394,80.242439,13.052394,80.272439,4.66,2022-11-03 23:50:00,2022-11-04 00:05:00,Cloudy,Low,Average,Drinks,scooter,0,No,Metropolitian
39640,Coimbatore,Zone11,20,4.7,11.001753,76.986241,11.041753,77.026241,6.23,2022-07-03 13:35:00,2022-07-03 13:40:00,Cloudy,High,poor,Snack,motorcycle,1,No,Metropolitian
39641,Ranchi,Zone09,23,4.9,23.351058,85.325731,23.431058,85.405731,12.07,2022-02-03 17:10:00,2022-02-03 17:15:00,Fog,Medium,Good,Snack,scooter,1,No,Metropolitian

In [13]:
numerical = ['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 
       'multiple_deliveries', 'distance_km', 'Prep_Time(min)', 'Order_hour',
       'isWeekend']

ohe_col = ['City', 'Zone', 'Weather_conditions',
       'Type_of_order', 'Type_of_vehicle',
       'City_Type','Order_day', 'Time_Of_Day']

ordinal_col = ['Road_traffic_density' , 'Vehicle_condition' , 'Festival',
       'delivery_rating_group' , 'age_group' , 'distance_group']

In [ ]:
Road_traffic_density = ['Low', 'Medium', 'High', 'Jam']
Vehicle_condition = ['poor', 'Average', 'Good' , 'Excellent']
Festival = ['No', 'Yes']
delivery_rating_group = ['Low', 'Medium', 'High']
age_group = ['Young', 'Adult', 'Senior']         
distance_group = ['Short Distance', 'Medium Distance', 'Long Distance']

In [ ]:
transformer = ColumnTransformer(
    transformers=[
        ("ohe" , OneHotEncoder(sparse_output=False , handle_unknown='ignore') , ohe_col),
        ('oe' , OrdinalEncoder(categories=[
            Road_traffic_density , Vehicle_condition,
            Festival , delivery_rating_group,
            age_group , distance_group
        ]) , ordinal_col),
        ('Scaling' , StandardScaler() , numerical)
    ],remainder='passthrough'
)

In [15]:
pipeline = Pipeline(
    [
        ("FeatureEngineering" , FeatureEngineering()),
        ("ColumnTransformer" , transformer)
    ]
)

In [16]:
X_train_trans = pipeline.fit_transform(X_train)
X_test_trans = pipeline.transform(X_test)

In [17]:
pt = PowerTransformer()

In [18]:
def objective(trial):
    with mlflow.start_run(nested=True):
        model_name = trial.suggest_categorical("model",["SVM","RF","KNN","GB","XGB","LGBM"])

        if model_name == "SVM":
            kernel_svm = trial.suggest_categorical("kernel_svm",["linear","poly","rbf"])
            if kernel_svm == "linear":
                c_linear = trial.suggest_float("c_linear",0,10)
                model = SVR(C=c_linear,kernel="linear")

            elif kernel_svm == "poly":
                c_poly = trial.suggest_float("c_poly",0,10)
                degree_poly = trial.suggest_int("degree_poly",1,5)
                model = SVR(C=c_poly,degree=degree_poly,
                            kernel="poly")

            else:
                c_rbf = trial.suggest_float("c_rbf",0,100)
                gamma_rbf = trial.suggest_float("gamma_rbf",0,10)
                model = SVR(C=c_rbf,gamma=gamma_rbf,
                            kernel="rbf")

        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,200)
            max_depth_rf = trial.suggest_int("max_depth_rf",2,20)
            rf = RandomForestRegressor(n_estimators=n_estimators_rf,
                                        max_depth=max_depth_rf,
                                        random_state=42,
                                        n_jobs=-1)
            model = TransformedTargetRegressor(regressor=rf , transformer=pt)

        elif model_name == "GB":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,200)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",0,1)
            max_depth_gb = trial.suggest_int("max_depth_gb",2,20)
            gb = GradientBoostingRegressor(n_estimators=n_estimators_gb,
                                                learning_rate=learning_rate_gb,
                                                max_depth=max_depth_gb,
                                                random_state=42)
            model = TransformedTargetRegressor(regressor=gb , transformer=pt)

        elif model_name == "KNN":
            n_neighbors_knn = trial.suggest_int("n_neighbors_knn",1,25)
            weights_knn = trial.suggest_categorical("weights_knn",["uniform","distance"])
            knn = KNeighborsRegressor(n_neighbors=n_neighbors_knn,
                                        weights=weights_knn,n_jobs=-1)
            model = TransformedTargetRegressor(regressor=knn , transformer=pt)

        elif model_name == "XGB":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,200)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",0.1,0.5)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",2,20)
            xgb = XGBRegressor(n_estimators=n_estimators_xgb,
                                    learning_rate=learning_rate_xgb,
                                    max_depth=max_depth_xgb,
                                    random_state=42,
                                    n_jobs=-1)
            model = TransformedTargetRegressor(regressor=xgb , transformer=pt)

        elif model_name == "LGBM":
            n_estimators_lgbm = trial.suggest_int("n_estimators_lgbm",10,200)
            learning_rate_lgbm = trial.suggest_float("learning_rate_lgbm",0.1,0.5)
            max_depth_lgbm = trial.suggest_int("max_depth_lgbm",2,20)
            lgbm = LGBMRegressor(n_estimators=n_estimators_lgbm,
                                    learning_rate=learning_rate_lgbm,
                                    max_depth=max_depth_lgbm,
                                    random_state=42)
            model = TransformedTargetRegressor(regressor=lgbm , transformer=pt)


        model.fit(X_train_trans , y_train)


        # log params
        mlflow.log_params(trial.params)
        mlflow.log_param("model_type" , model_name)

        

        # get the predictions
        y_pred_test = model.predict(X_test_trans)

        # calculate the error
        error = mean_absolute_error(y_test,y_pred_test)

        # log model_name
        mlflow.log_param("model",model_name)

        # log error
        mlflow.log_metric("MAE",error)

        return error

In [ ]:
study = optuna.create_study(direction='minimize')

with mlflow.start_run(run_name="best_model"):
    # optimize the objective function
    study.optimize(objective , n_trials=50 , n_jobs=-1 , show_progress_bar=True)

    # log the best params
    mlflow.log_params(study.best_params)

    # log best score
    mlflow.log_metric("best_score" , study.best_value)

    # training the lgbm on best param
    best_xgb = XGBRegressor(**study.best_params)

    best_model = TransformedTargetRegressor(regressor=best_xgb , transformer=pt)

    best_model.fit(X_train_trans , y_train)

    y_pred_train = best_model.predict(X_train_trans)
    y_pred_test = best_model.predict(X_test_trans)

    scores = cross_val_score(
        best_model,
        X_train_trans,
        y_train,
        scoring="neg_mean_absolute_error",
        cv=5,n_jobs=-1
    )

    # logging metrics
    mlflow.log_metric("Training_error" ,mean_absolute_error(y_train ,y_pred_train))
    mlflow.log_metric("Test_error" ,mean_absolute_error(y_test ,y_pred_test))
    mlflow.log_metric("Training_r2" ,r2_score(y_train ,y_pred_train))
    mlflow.log_metric("Test_r2" ,r2_score(y_test ,y_pred_test))
    mlflow.log_metric("cross_val" , -scores.mean())
    
    # log the best model 
    mlflow.sklearn.log_model(best_xgb , artifact_path="Model_Selection")

[I 2026-07-01 22:40:20,728] A new study created in memory with name: no-name-85f47f91-c230-47fb-ae17-dd304338339a
  0%|          | 0/50 [00:00<?, ?it/s]

🏃 View run honorable-hare-937 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/ee065c9adc194220a1c291b756fdb1bd
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run gifted-hawk-806 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/b6641c78d75c4053a8cd841461af33c7
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run likeable-bird-78 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/45399be25b6344b9a2d828f70f381e14
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 15. Best value: 3.0547:   2%|▏         | 1/50 [00:48<39:28, 48.34s/it]

[I 2026-07-01 22:41:09,889] Trial 15 finished with value: 3.0546997090644923 and parameters: {'model': 'RF', 'n_estimators_rf': 68, 'max_depth_rf': 13}. Best is trial 15 with value: 3.0546997090644923.

Best trial: 15. Best value: 3.0547:   4%|▍         | 2/50 [00:52<17:49, 22.28s/it]

[I 2026-07-01 22:41:13,924] Trial 6 finished with value: 5.808824276091333 and parameters: {'model': 'RF', 'n_estimators_rf': 192, 'max_depth_rf': 2}. Best is trial 15 with value: 3.0546997090644923.
🏃 View run worried-croc-474 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/603803d682bd4253aac9603ce5eec8ce
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run fun-frog-950 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/24784cd2c22e43fb83d686893eaef32a
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 15. Best value: 3.0547:   6%|▌         | 3/50 [01:04<13:43, 17.53s/it]

[I 2026-07-01 22:41:25,801] Trial 3 finished with value: 5.807351151713725 and parameters: {'model': 'RF', 'n_estimators_rf': 138, 'max_depth_rf': 2}. Best is trial 15 with value: 3.0546997090644923.

Best trial: 15. Best value: 3.0547:   8%|▊         | 4/50 [01:05<08:38, 11.27s/it]

[I 2026-07-01 22:41:27,482] Trial 5 finished with value: 4.479551209171519 and parameters: {'model': 'KNN', 'n_neighbors_knn': 11, 'weights_knn': 'distance'}. Best is trial 15 with value: 3.0546997090644923.
🏃 View run calm-rook-844 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/e557a405ffcf400da80c6ae87ec44ed9
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 15. Best value: 3.0547:  10%|█         | 5/50 [01:17<08:39, 11.53s/it]

[I 2026-07-01 22:41:39,471] Trial 4 finished with value: 4.562441743678607 and parameters: {'model': 'KNN', 'n_neighbors_knn': 6, 'weights_knn': 'distance'}. Best is trial 15 with value: 3.0546997090644923.
🏃 View run beautiful-worm-245 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/d4b0bf959d3140ae87ac592cc9b8c16b
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run luminous-shad-81 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/b51bc1d2078a4330b9749e530124cf8b
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 15. Best value: 3.0547:  12%|█▏        | 6/50 [01:32<09:08, 12.47s/it]

[I 2026-07-01 22:41:53,756] Trial 2 finished with value: 4.4642477083638585 and parameters: {'model': 'KNN', 'n_neighbors_knn': 17, 'weights_knn': 'distance'}. Best is trial 15 with value: 3.0546997090644923.
🏃 View run secretive-frog-131 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/a69c5248ce91405d874f492cd4c40079
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 15. Best value: 3.0547:  14%|█▍        | 7/50 [01:41<08:17, 11.57s/it]

[I 2026-07-01 22:42:03,484] Trial 0 finished with value: 3.2647760609586185 and parameters: {'model': 'GB', 'n_estimators_gb': 17, 'learning_rate_gb': 0.6346506046445821, 'max_depth_gb': 6}. Best is trial 15 with value: 3.0546997090644923.
🏃 View run nimble-crane-894 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/7e97a61418a247b0a53f76bd6b3f1feb
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 15. Best value: 3.0547:  16%|█▌        | 8/50 [01:53<08:11, 11.70s/it]

[I 2026-07-01 22:42:15,465] Trial 9 finished with value: 3.2507174015045166 and parameters: {'model': 'XGB', 'n_estimators_xgb': 186, 'learning_rate_xgb': 0.15194987795441542, 'max_depth_xgb': 4}. Best is trial 15 with value: 3.0546997090644923.
🏃 View run indecisive-deer-463 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/2c0268ee1c0b47ce8001d2c76646f995
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  18%|█▊        | 9/50 [02:00<06:50, 10.02s/it]

[I 2026-07-01 22:42:21,789] Trial 8 finished with value: 3.028179407119751 and parameters: {'model': 'XGB', 'n_estimators_xgb': 19, 'learning_rate_xgb': 0.24015669612328497, 'max_depth_xgb': 10}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  20%|██        | 10/50 [02:02<04:58,  7.47s/it]

[I 2026-07-01 22:42:23,555] Trial 14 finished with value: 3.0630640520040178 and parameters: {'model': 'RF', 'n_estimators_rf': 154, 'max_depth_rf': 20}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  22%|██▏       | 11/50 [02:04<03:50,  5.91s/it]

[I 2026-07-01 22:42:25,909] Trial 7 finished with value: 3.9742624044165282 and parameters: {'model': 'GB', 'n_estimators_gb': 23, 'learning_rate_gb': 0.8495778378856094, 'max_depth_gb': 15}. Best is trial 8 with value: 3.028179407119751.
🏃 View run gentle-chimp-929 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/16b01d657a89460289e02f5daec85185
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  24%|██▍       | 12/50 [02:17<05:13,  8.25s/it]

[I 2026-07-01 22:42:39,528] Trial 11 finished with value: 4.163160016099038 and parameters: {'model': 'GB', 'n_estimators_gb': 123, 'learning_rate_gb': 0.9101122927498039, 'max_depth_gb': 8}. Best is trial 8 with value: 3.028179407119751.
🏃 View run masked-auk-115 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/1ed781c961a0456da7e5fb5f423014a6
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run adaptable-steed-680 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/4190d2f9145d444b9d4ab734ffb436bb
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run spiffy-wasp-941 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/078b09e7d4ca4afda78d12238969071d
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
Best trial: 8. Best value: 3.02818:  26%|██▌       | 13/50 [02:57<11:00, 17.85s/it]

[I 2026-07-01 22:43:19,465] Trial 21 finished with value: 3.1432474335042557 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 134, 'learning_rate_lgbm': 0.3966634999034299, 'max_depth_lgbm': 8}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  28%|██▊       | 14/50 [03:00<07:55, 13.20s/it]

[I 2026-07-01 22:43:21,922] Trial 19 finished with value: 4.506687156915804 and parameters: {'model': 'KNN', 'n_neighbors_knn': 9, 'weights_knn': 'uniform'}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  30%|███       | 15/50 [03:01<05:38,  9.68s/it]

[I 2026-07-01 22:43:23,458] Trial 18 finished with value: 4.46336163697803 and parameters: {'model': 'KNN', 'n_neighbors_knn': 16, 'weights_knn': 'distance'}. Best is trial 8 with value: 3.028179407119751.
🏃 View run flawless-shrimp-986 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/a3998cf0e11640fd98e118b7a2b66078
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
Best trial: 8. Best value: 3.02818:  32%|███▏      | 16/50 [03:17<06:34, 11.61s/it]

[I 2026-07-01 22:43:39,534] Trial 20 finished with value: 3.0491714477539062 and parameters: {'model': 'XGB', 'n_estimators_xgb': 111, 'learning_rate_xgb': 0.17815134309717431, 'max_depth_xgb': 8}. Best is trial 8 with value: 3.028179407119751.
🏃 View run resilient-jay-507 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/87edaa89f5ce4044a24236a88a301138
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run auspicious-fawn-118 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/738dfce79f8f4de88882e14db2b9bf69
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  34%|███▍      | 17/50 [03:40<08:09, 14.83s/it]

[I 2026-07-01 22:44:01,859] Trial 22 finished with value: 3.1161068266925427 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 41, 'learning_rate_lgbm': 0.12385459440278718, 'max_depth_lgbm': 7}. Best is trial 8 with value: 3.028179407119751.
🏃 View run gifted-robin-179 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/2472b16d8101417580e3644890babf82
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run polite-roo-101 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/5d9b27e06e1b42508c78fabf4b420958
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  36%|███▌      | 18/50 [03:56<08:05, 15.17s/it]

[I 2026-07-01 22:44:17,832] Trial 23 finished with value: 3.0674453920740157 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 87, 'learning_rate_lgbm': 0.18820485454230412, 'max_depth_lgbm': 9}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  38%|███▊      | 19/50 [03:57<05:44, 11.11s/it]

[I 2026-07-01 22:44:19,474] Trial 27 finished with value: 3.274355411529541 and parameters: {'model': 'XGB', 'n_estimators_xgb': 10, 'learning_rate_xgb': 0.3820501585481603, 'max_depth_xgb': 17}. Best is trial 8 with value: 3.028179407119751.
🏃 View run mysterious-pig-322 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/90dc136bd3c7403e8384e458a7584635
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  40%|████      | 20/50 [04:13<06:17, 12.57s/it]

[I 2026-07-01 22:44:35,445] Trial 17 finished with value: 3.0764271267106804 and parameters: {'model': 'GB', 'n_estimators_gb': 58, 'learning_rate_gb': 0.03963440504296056, 'max_depth_gb': 11}. Best is trial 8 with value: 3.028179407119751.
🏃 View run thoughtful-cod-83 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/740aa2a288c0460b8feae3050c9dbc91
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  42%|████▏     | 21/50 [04:24<05:45, 11.92s/it]

[I 2026-07-01 22:44:45,851] Trial 25 finished with value: 3.1814948830651977 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 117, 'learning_rate_lgbm': 0.4757736897707785, 'max_depth_lgbm': 12}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  44%|████▍     | 22/50 [04:33<05:14, 11.25s/it]

[I 2026-07-01 22:44:55,515] Trial 29 finished with value: 3.262000799179077 and parameters: {'model': 'XGB', 'n_estimators_xgb': 17, 'learning_rate_xgb': 0.3913127410211342, 'max_depth_xgb': 16}. Best is trial 8 with value: 3.028179407119751.
🏃 View run shivering-colt-672 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/0b46c0335d664ef4b1b82065ab39d000
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run invincible-dog-365 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/e3f0c1221785461db9ad4fa92509335e
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run agreeable-snail-629 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/e510f9c50c334ec2b16f2786672b6cb2
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5
🏃 View run clumsy-koi-414 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/4ef3e2824c0545439a0f6eb13daa05ad
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  46%|████▌     | 23/50 [04:58<06:48, 15.14s/it]

[I 2026-07-01 22:45:19,742] Trial 1 finished with value: 4.076419270054326 and parameters: {'model': 'GB', 'n_estimators_gb': 180, 'learning_rate_gb': 0.9085092236158803, 'max_depth_gb': 12}. Best is trial 8 with value: 3.028179407119751.
🏃 View run abrasive-panda-629 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/125f283d7c5149898bbfd8bb4981d9d1
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  48%|████▊     | 24/50 [05:02<05:05, 11.76s/it]

[I 2026-07-01 22:45:23,622] Trial 28 finished with value: 3.0567703247070312 and parameters: {'model': 'XGB', 'n_estimators_xgb': 23, 'learning_rate_xgb': 0.23050944211270075, 'max_depth_xgb': 11}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  50%|█████     | 25/50 [05:05<03:54,  9.38s/it]

[I 2026-07-01 22:45:27,463] Trial 31 finished with value: 3.0633769035339355 and parameters: {'model': 'XGB', 'n_estimators_xgb': 29, 'learning_rate_xgb': 0.2275926757096986, 'max_depth_xgb': 11}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  52%|█████▏    | 26/50 [05:09<03:06,  7.76s/it]

[I 2026-07-01 22:45:31,457] Trial 30 finished with value: 3.060668468475342 and parameters: {'model': 'XGB', 'n_estimators_xgb': 23, 'learning_rate_xgb': 0.2418867759083151, 'max_depth_xgb': 11}. Best is trial 8 with value: 3.028179407119751.

Best trial: 8. Best value: 3.02818:  54%|█████▍    | 27/50 [05:17<03:00,  7.83s/it]

[I 2026-07-01 22:45:39,444] Trial 33 finished with value: 3.067012071609497 and parameters: {'model': 'XGB', 'n_estimators_xgb': 84, 'learning_rate_xgb': 0.1929462493769718, 'max_depth_xgb': 9}. Best is trial 8 with value: 3.028179407119751.
🏃 View run welcoming-skink-698 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/572565122f464589b0d58bbbdf9ca6ce
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  56%|█████▌    | 28/50 [10:01<33:10, 90.46s/it]

[I 2026-07-01 22:50:22,681] Trial 38 finished with value: 4.414318684926684 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 0.1116587178813031, 'degree_poly': 3}. Best is trial 8 with value: 3.028179407119751.
🏃 View run omniscient-foal-45 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/39d6e9da88ec45f0bc3bbf83a098fbaf
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  58%|█████▊    | 29/50 [13:04<41:27, 118.43s/it]

[I 2026-07-01 22:53:26,386] Trial 40 finished with value: 4.56803473040947 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 0.9271558455945765}. Best is trial 8 with value: 3.028179407119751.
🏃 View run sedate-loon-541 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/3a8c6a3ceeaa439d8d9421ab5a77aac2
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  60%|██████    | 30/50 [13:17<28:52, 86.62s/it]

[I 2026-07-01 22:53:38,775] Trial 44 finished with value: 3.070617268077967 and parameters: {'model': 'RF', 'n_estimators_rf': 27, 'max_depth_rf': 14}. Best is trial 8 with value: 3.028179407119751.
🏃 View run upset-shoat-277 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/6c2a5e25f5e246c3981679824c2fd70e
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  62%|██████▏   | 31/50 [13:31<20:34, 64.98s/it]

[I 2026-07-01 22:53:53,268] Trial 45 finished with value: 3.072795205674834 and parameters: {'model': 'RF', 'n_estimators_rf': 59, 'max_depth_rf': 11}. Best is trial 8 with value: 3.028179407119751.
🏃 View run resilient-crab-968 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/fc729ec9253a4cc599e65e442b59acaa
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  64%|██████▍   | 32/50 [14:35<19:21, 64.55s/it]

[I 2026-07-01 22:54:56,805] Trial 46 finished with value: 3.134026288986206 and parameters: {'model': 'XGB', 'n_estimators_xgb': 98, 'learning_rate_xgb': 0.2879133660225223, 'max_depth_xgb': 6}. Best is trial 8 with value: 3.028179407119751.
🏃 View run unleashed-dove-241 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/dbbdb862482a4d2daa26af2cf8e20803
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  66%|██████▌   | 33/50 [14:48<13:57, 49.27s/it]

[I 2026-07-01 22:55:10,425] Trial 34 finished with value: 7.38880558195857 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 0.8878320274912284, 'gamma_rbf': 2.010338148735842}. Best is trial 8 with value: 3.028179407119751.
🏃 View run delightful-ox-571 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/a1bf4f0ecbb348f89530ec70cac27f58
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  68%|██████▊   | 34/50 [15:51<14:12, 53.26s/it]

[I 2026-07-01 22:56:12,990] Trial 47 finished with value: 3.0414726734161377 and parameters: {'model': 'XGB', 'n_estimators_xgb': 155, 'learning_rate_xgb': 0.12654096359067346, 'max_depth_xgb': 8}. Best is trial 8 with value: 3.028179407119751.
🏃 View run defiant-sloth-142 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/9c0ec620c51e45ad8a0de38b986580e9
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  70%|███████   | 35/50 [16:07<10:30, 42.03s/it]

[I 2026-07-01 22:56:28,834] Trial 24 finished with value: 4.567952823858103 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 3.691461372250299}. Best is trial 8 with value: 3.028179407119751.
🏃 View run enchanting-ray-358 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/9aeef2a6d2434af8bec0dae7770b80a5
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  72%|███████▏  | 36/50 [16:09<06:59, 29.98s/it]

[I 2026-07-01 22:56:30,681] Trial 48 finished with value: 3.041837692260742 and parameters: {'model': 'XGB', 'n_estimators_xgb': 142, 'learning_rate_xgb': 0.13211615683561995, 'max_depth_xgb': 8}. Best is trial 8 with value: 3.028179407119751.
🏃 View run fearless-hawk-635 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/1c8fd7711b554031ac3966fed491a41b
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  74%|███████▍  | 37/50 [16:12<04:45, 21.97s/it]

[I 2026-07-01 22:56:33,960] Trial 49 finished with value: 3.058760643005371 and parameters: {'model': 'XGB', 'n_estimators_xgb': 161, 'learning_rate_xgb': 0.11733521329991298, 'max_depth_xgb': 7}. Best is trial 8 with value: 3.028179407119751.
🏃 View run languid-conch-542 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/b67be305fc6944fba35a9fd507c34b3a
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  76%|███████▌  | 38/50 [16:50<05:19, 26.66s/it]

[I 2026-07-01 22:57:11,564] Trial 32 finished with value: 3.784443786509297 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 2.9629250932225704, 'degree_poly': 3}. Best is trial 8 with value: 3.028179407119751.
🏃 View run receptive-colt-93 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/974bfc0ed2bd4220993ad5042f9cdf65
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  78%|███████▊  | 39/50 [17:15<04:49, 26.34s/it]

[I 2026-07-01 22:57:37,163] Trial 13 finished with value: 4.1005045950568215 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 1.7829827612576299, 'degree_poly': 5}. Best is trial 8 with value: 3.028179407119751.
🏃 View run welcoming-snipe-362 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/846ae937f05f4295ab629d2ea49e5558
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  80%|████████  | 40/50 [17:56<05:07, 30.73s/it]

[I 2026-07-01 22:58:18,124] Trial 12 finished with value: 4.567461291859312 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 7.7478867345105416}. Best is trial 8 with value: 3.028179407119751.
🏃 View run bemused-skunk-880 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/d4113919b5844327accd3cf2ce1aa250
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  82%|████████▏ | 41/50 [18:53<05:47, 38.65s/it]

[I 2026-07-01 22:59:15,263] Trial 43 finished with value: 7.389881223078612 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 3.559510761640915, 'gamma_rbf': 2.5308204657592626}. Best is trial 8 with value: 3.028179407119751.
🏃 View run fun-vole-74 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/e42a496c05334d4d85879db3c48327bb
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  84%|████████▍ | 42/50 [18:57<03:46, 28.25s/it]

[I 2026-07-01 22:59:19,255] Trial 36 finished with value: 3.8628072526201653 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 3.006233290622936, 'degree_poly': 4}. Best is trial 8 with value: 3.028179407119751.
🏃 View run wise-ape-986 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/1add1aa3b6574d0f95445fa94cf79df5
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  86%|████████▌ | 43/50 [19:41<03:50, 32.95s/it]

[I 2026-07-01 23:00:03,167] Trial 10 finished with value: 7.422479655793863 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 18.66987398724892, 'gamma_rbf': 6.57516482830467}. Best is trial 8 with value: 3.028179407119751.
🏃 View run hilarious-deer-799 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/826d270df5b5471f8aeb605cd7efb01e
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  88%|████████▊ | 44/50 [19:58<02:49, 28.23s/it]

[I 2026-07-01 23:00:20,387] Trial 35 finished with value: 7.386555418114968 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 8.953721986873703, 'gamma_rbf': 6.5222174197631535}. Best is trial 8 with value: 3.028179407119751.
🏃 View run enthused-dolphin-752 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/81331b845b6b475f8016c94ab7336b3c
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  90%|█████████ | 45/50 [21:41<04:13, 50.68s/it]

[I 2026-07-01 23:02:03,431] Trial 26 finished with value: 4.567460955399594 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 9.953616565329844}. Best is trial 8 with value: 3.028179407119751.
🏃 View run adaptable-auk-590 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/1662cd783e414c4bad465da133e2eb97
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  92%|█████████▏| 46/50 [21:58<02:42, 40.53s/it]

[I 2026-07-01 23:02:20,297] Trial 42 finished with value: 4.567491115552631 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 9.692922917239585}. Best is trial 8 with value: 3.028179407119751.
🏃 View run serious-pug-397 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/96e131160c4d4f228ec49426a52d4ba9
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  94%|█████████▍| 47/50 [22:08<01:33, 31.29s/it]

[I 2026-07-01 23:02:30,024] Trial 39 finished with value: 7.4321653182070095 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 64.55721189543625, 'gamma_rbf': 9.38567014182939}. Best is trial 8 with value: 3.028179407119751.
🏃 View run bouncy-cod-745 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/ca3eeffd61a742f5be65ca2d41ff6972
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  96%|█████████▌| 48/50 [22:38<01:01, 30.94s/it]

[I 2026-07-01 23:03:00,131] Trial 37 finished with value: 7.40833575044169 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 15.262197305669375, 'gamma_rbf': 9.887883205834274}. Best is trial 8 with value: 3.028179407119751.
🏃 View run upset-dolphin-817 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/3dee5e05f75a408884cc1fd953ad2041
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818:  98%|█████████▊| 49/50 [24:45<00:59, 59.59s/it]

[I 2026-07-01 23:05:06,593] Trial 16 finished with value: 4.062758319094305 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 5.5217352840803455, 'degree_poly': 5}. Best is trial 8 with value: 3.028179407119751.
🏃 View run angry-mink-827 at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/64c5cd47a11f4d129cf7974c6123dad8
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

Best trial: 8. Best value: 3.02818: 100%|██████████| 50/50 [27:45<00:00, 33.31s/it]

[I 2026-07-01 23:08:06,816] Trial 41 finished with value: 4.096670094198045 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 7.981483589730658, 'degree_poly': 5}. Best is trial 8 with value: 3.028179407119751.

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xgboost\training.py:199: UserWarning: [23:08:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "learning_rate_xgb", "max_depth_xgb", "model", "n_estimators_xgb" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[W 2026-07-01 23:08:13,919] Your study has only completed trials with missing parameters.
2026/07/01 23:08:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/01 23:08:21 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run best_model at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5/runs/b5e247c29c4b4d20814384191a1efcac
🧪 View experiment at: https://dagshub.com/mridul0010/Delivery-Time-Analysis-Prediction.mlflow/#/experiments/5

In [20]:
study.best_value

3.028179407119751

In [22]:
study.best_params

{'model': 'XGB',
 'n_estimators_xgb': 19,
 'learning_rate_xgb': 0.24015669612328497,
 'max_depth_xgb': 10}

In [25]:
study.trials_dataframe().head()

,number,value,datetime_start,datetime_complete,duration,params_c_linear,params_c_poly,params_c_rbf,params_degree_poly,params_gamma_rbf,params_kernel_svm,params_learning_rate_gb,params_learning_rate_lgbm,params_learning_rate_xgb,params_max_depth_gb,params_max_depth_lgbm,params_max_depth_rf,params_max_depth_xgb,params_model,params_n_estimators_gb,params_n_estimators_lgbm,params_n_estimators_rf,params_n_estimators_xgb,params_n_neighbors_knn,params_weights_knn,state
0,0,3.264776,2026-07-01 22:40:21.558746,2026-07-01 22:42:03.484280,0 days 00:01:41.925534,NaN,NaN,NaN,NaN,NaN,NaN,0.634651,NaN,NaN,6.0,NaN,NaN,NaN,GB,17.0,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,4.076419,2026-07-01 22:40:21.559535,2026-07-01 22:45:19.742331,0 days 00:04:58.182796,NaN,NaN,NaN,NaN,NaN,NaN,0.908509,NaN,NaN,12.0,NaN,NaN,NaN,GB,180.0,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,4.464248,2026-07-01 22:40:21.562678,2026-07-01 22:41:53.756217,0 days 00:01:32.193539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KNN,NaN,NaN,NaN,NaN,17.0,distance,COMPLETE
3,3,5.807351,2026-07-01 22:40:21.564946,2026-07-01 22:41:25.801324,0 days 00:01:04.236378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,RF,NaN,NaN,138.0,NaN,NaN,NaN,COMPLETE
4,4,4.562442,2026-07-01 22:40:21.569808,2026-07-01 22:41:39.471416,0 days 00:01:17.901608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KNN,NaN,NaN,NaN,NaN,6.0,distance,COMPLETE

In [27]:
study.trials_dataframe()['params_model'].value_counts()

params_model
SVM     17
XGB     13
RF       6
GB       5
KNN      5
LGBM     4
Name: count, dtype: int64

In [29]:
best_xgb = XGBRegressor(**study.best_params)

model = TransformedTargetRegressor(regressor=best_xgb , transformer=pt)

model.fit(X_train_trans , y_train)

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\xgboost\training.py:199: UserWarning:

[23:26:34] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "learning_rate_xgb", "max_depth_xgb", "model", "n_estimators_xgb" } are not used.

TransformedTargetRegressor(regressor=XGBRegressor(base_score=None, booster=None,
                                                  callbacks=None,
                                                  colsample_bylevel=None,
                                                  colsample_bynode=None,
                                                  colsample_bytree=None,
                                                  device=None,
                                                  early_stopping_rounds=None,
                                                  enable_categorical=False,
                                                  eval_metric=None,
                                                  feature_types=None,
                                                  feature_weights=None,
                                                  gamma=None, grow_policy=None,
                                                  importance_type=None,
                                                  interaction_constraints=None,
                                                  learning_rate=None,
                                                  learning_rate_xgb=0.24015669612328497,
                                                  max_bin=None,
                                                  max_cat_threshold=None,
                                                  max_cat_to_onehot=None,
                                                  max_delta_step=None,
                                                  max_depth=None,
                                                  max_depth_xgb=10,
                                                  max_leaves=None,
                                                  min_child_weight=None,
                                                  missing=nan, model='XGB',
                                                  monotone_constraints=None,
                                                  multi_strategy=None, ...),
                           transformer=PowerTransformer())

In [30]:
y_pred = model.predict(X_test_trans)

r2_score(y_test , y_pred)

0.8177204132080078

In [31]:
study.trials_dataframe().head()

,number,value,datetime_start,datetime_complete,duration,params_c_linear,params_c_poly,params_c_rbf,params_degree_poly,params_gamma_rbf,params_kernel_svm,params_learning_rate_gb,params_learning_rate_lgbm,params_learning_rate_xgb,params_max_depth_gb,params_max_depth_lgbm,params_max_depth_rf,params_max_depth_xgb,params_model,params_n_estimators_gb,params_n_estimators_lgbm,params_n_estimators_rf,params_n_estimators_xgb,params_n_neighbors_knn,params_weights_knn,state
0,0,3.264776,2026-07-01 22:40:21.558746,2026-07-01 22:42:03.484280,0 days 00:01:41.925534,NaN,NaN,NaN,NaN,NaN,NaN,0.634651,NaN,NaN,6.0,NaN,NaN,NaN,GB,17.0,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,4.076419,2026-07-01 22:40:21.559535,2026-07-01 22:45:19.742331,0 days 00:04:58.182796,NaN,NaN,NaN,NaN,NaN,NaN,0.908509,NaN,NaN,12.0,NaN,NaN,NaN,GB,180.0,NaN,NaN,NaN,NaN,NaN,COMPLETE
2,2,4.464248,2026-07-01 22:40:21.562678,2026-07-01 22:41:53.756217,0 days 00:01:32.193539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KNN,NaN,NaN,NaN,NaN,17.0,distance,COMPLETE
3,3,5.807351,2026-07-01 22:40:21.564946,2026-07-01 22:41:25.801324,0 days 00:01:04.236378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,RF,NaN,NaN,138.0,NaN,NaN,NaN,COMPLETE
4,4,4.562442,2026-07-01 22:40:21.569808,2026-07-01 22:41:39.471416,0 days 00:01:17.901608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KNN,NaN,NaN,NaN,NaN,6.0,distance,COMPLETE

In [32]:
plot_optimization_history(study)