In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV , KFold , cross_val_score
from sklearn.linear_model import LinearRegression 
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
from sklearn.compose import ColumnTransformer , TransformedTargetRegressor
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder , PowerTransformer
from sklearn.base import BaseEstimator , TransformerMixin
import optuna
from lightgbm import LGBMRegressor
import mlflow
import dagshub
from optuna.visualization import plot_optimization_history, plot_param_importances, plot_parallel_coordinate , plot_slice

In [2]:
dagshub.init(repo_owner="mridul0010" , repo_name="food-delivery-time-prediction" , mlflow=True)

Accessing as mridul0010

Initialized MLflow to track repo "mridul0010/food-delivery-time-prediction"

Repository mridul0010/food-delivery-time-prediction initialized!

In [3]:
mlflow.set_tracking_uri("https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow")

In [4]:
mlflow.set_experiment("4. Model Selection")

<Experiment: artifact_location='mlflow-artifacts:/e4b0fb1e261d4dc7a0a2eeb8fb8f24e9', creation_time=1783251238084, effective_trace_archival_retention=None, experiment_id='4', last_update_time=1783251238084, lifecycle_stage='active', name='4. Model Selection', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

In [5]:
df = pd.read_csv('../data/Cleaned Delivery Dataset.csv')

In [6]:
pd.set_option('display.max_columns' , None)

In [7]:
df.drop(columns=['Delivery_Agent'] , inplace=True)

In [8]:
df['Order_Datetime'] = pd.to_datetime(df['Order_Datetime'])
df['Pickup_Datetime'] = pd.to_datetime(df['Pickup_Datetime'])

In [9]:
class FeatureEngineering(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.rating_bins = None

    def fit(self, X, y=None):
        X = X.copy()
        
        # Store bins for consistent transformation
        self.rating_bins = pd.qcut(
            X['Delivery_person_Ratings'],
            q=3,
            retbins=True,
            duplicates='drop'
        )[1]
        
        return self

    def transform(self, X):
        X = X.copy()

        # Datetime conversion
        X['Order_Datetime'] = pd.to_datetime(X['Order_Datetime'], errors='coerce')
        X['Pickup_Datetime'] = pd.to_datetime(X['Pickup_Datetime'], errors='coerce')

        # Rating group
        X["delivery_rating_group"] = pd.cut(
            X['Delivery_person_Ratings'],
            bins=self.rating_bins,
            labels=['Low', 'Medium', 'High'],
            include_lowest=True
        )

        # Age group
        X["age_group"] = pd.cut(
            X['Delivery_person_Age'],
            bins=[14, 25, 35, 60],
            labels=['Young', 'Adult', 'Senior']
        )

        # Distance group
        X["distance_group"] = pd.cut(
            X['distance_km'],
            bins=[0, 5, 10, 25],
            labels=['Short Distance', 'Medium Distance', 'Long Distance']
        )

        # Time features
        X['Prep_Time(min)'] = (
            X['Pickup_Datetime'] - X['Order_Datetime']
        ).dt.total_seconds() / 60

        X['Order_hour'] = X['Order_Datetime'].dt.hour
        X['Order_day'] = X['Order_Datetime'].dt.day_name()

        X['isWeekend'] = X['Order_day'].isin(["Saturday", "Sunday"]).astype(int)

        X['Time_Of_Day'] = pd.cut(
            X['Order_hour'],
            bins=[0, 6, 12, 18, 24],
            labels=["Night", "Morning", "Afternoon", "Evening"],
            include_lowest=True
        )

        # Drop raw datetime
        X = X.drop(columns=['Order_Datetime', 'Pickup_Datetime'], errors='ignore')

        return X

    def get_feature_names_out(self , input_features = None):
        return input_features

In [10]:
X = df.drop(columns=['Time_taken (min)'])
y = df['Time_taken (min)']

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

In [12]:
X

,City,Zone,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,distance_km,Order_Datetime,Pickup_Datetime,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type
0,Dehradun,Zone17,36,4.2,30.327968,78.046106,30.397968,78.116106,10.28,2022-12-02 21:55:00,2022-12-02 22:10:00,Fog,Jam,Good,Snack,motorcycle,3,No,Metropolitian
1,Kochi,Zone16,21,4.7,10.003064,76.307589,10.043064,76.347589,6.24,2022-02-13 14:55:00,2022-02-13 15:05:00,Stormy,High,Average,Meal,motorcycle,1,No,Metropolitian
2,Pune,Zone13,23,4.7,18.562450,73.916619,18.652450,74.006619,13.79,2022-04-03 17:30:00,2022-04-03 17:40:00,Sandstorms,Medium,Average,Drinks,scooter,1,No,Metropolitian
3,Ludhiana,Zone15,34,4.3,30.899584,75.809346,30.919584,75.829346,2.93,2022-02-13 09:20:00,2022-02-13 09:30:00,Sandstorms,Low,poor,Buffet,motorcycle,0,No,Metropolitian
4,Kanpur,Zone14,24,4.7,26.463504,80.372929,26.593504,80.502929,19.40,2022-02-14 19:50:00,2022-02-14 20:05:00,Fog,Jam,Average,Snack,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39637,Bangalore,Zone16,28,4.9,13.029198,77.570997,13.059198,77.600997,4.66,2022-03-30 21:55:00,2022-03-30 22:05:00,Sandstorms,Jam,Average,Meal,scooter,1,No,Metropolitian
39638,Ranchi,Zone16,35,4.2,23.371292,85.327872,23.481292,85.437872,16.60,2022-08-03 21:45:00,2022-08-03 21:55:00,Windy,Jam,Good,Drinks,motorcycle,1,No,Metropolitian
39639,Chennai,Zone08,30,4.9,13.022394,80.242439,13.052394,80.272439,4.66,2022-11-03 23:50:00,2022-11-04 00:05:00,Cloudy,Low,Average,Drinks,scooter,0,No,Metropolitian
39640,Coimbatore,Zone11,20,4.7,11.001753,76.986241,11.041753,77.026241,6.23,2022-07-03 13:35:00,2022-07-03 13:40:00,Cloudy,High,poor,Snack,motorcycle,1,No,Metropolitian
39641,Ranchi,Zone09,23,4.9,23.351058,85.325731,23.431058,85.405731,12.07,2022-02-03 17:10:00,2022-02-03 17:15:00,Fog,Medium,Good,Snack,scooter,1,No,Metropolitian

In [13]:
numerical = ['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 
       'multiple_deliveries', 'distance_km', 'Prep_Time(min)', 'Order_hour',
       'isWeekend']

ohe_col = ['City', 'Zone', 'Weather_conditions',
       'Type_of_order', 'Type_of_vehicle',
       'City_Type','Order_day', 'Time_Of_Day']

ordinal_col = ['Road_traffic_density' , 'Vehicle_condition' , 'Festival',
       'delivery_rating_group' , 'age_group' , 'distance_group']

In [14]:
Road_traffic_density = ['Low', 'Medium', 'High', 'Jam']
Vehicle_condition = ['poor', 'Average', 'Good' , 'Excellent']
Festival = ['No', 'Yes']
delivery_rating_group = ['Low', 'Medium', 'High']
age_group = ['Young', 'Adult', 'Senior']         
distance_group = ['Short Distance', 'Medium Distance', 'Long Distance']

In [15]:
transformer = ColumnTransformer(
    transformers=[
        ("ohe" , OneHotEncoder(sparse_output=False , handle_unknown='ignore') , ohe_col),
        ('oe' , OrdinalEncoder(categories=[
            Road_traffic_density , Vehicle_condition,
            Festival , delivery_rating_group,
            age_group , distance_group
        ]) , ordinal_col),
        ('Scaling' , StandardScaler() , numerical)
    ],remainder='passthrough'
)

In [16]:
pipeline = Pipeline(
    [
        ("FeatureEngineering" , FeatureEngineering()),
        ("ColumnTransformer" , transformer)
    ]
)

In [17]:
X_train_trans = pipeline.fit_transform(X_train)
X_test_trans = pipeline.transform(X_test)

In [18]:
pt = PowerTransformer()

In [19]:
def objective(trial):
    with mlflow.start_run(nested=True):
        model_name = trial.suggest_categorical("model",["SVM","RF","KNN","GB","XGB","LGBM"])

        if model_name == "SVM":
            kernel_svm = trial.suggest_categorical("kernel_svm",["linear","poly","rbf"])
            if kernel_svm == "linear":
                c_linear = trial.suggest_float("c_linear",0,10)
                model = SVR(C=c_linear,kernel="linear")

            elif kernel_svm == "poly":
                c_poly = trial.suggest_float("c_poly",0,10)
                degree_poly = trial.suggest_int("degree_poly",1,5)
                model = SVR(C=c_poly,degree=degree_poly,
                            kernel="poly")

            else:
                c_rbf = trial.suggest_float("c_rbf",0,100)
                gamma_rbf = trial.suggest_float("gamma_rbf",0,10)
                model = SVR(C=c_rbf,gamma=gamma_rbf,
                            kernel="rbf")

        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,200)
            max_depth_rf = trial.suggest_int("max_depth_rf",2,20)
            rf = RandomForestRegressor(n_estimators=n_estimators_rf,
                                        max_depth=max_depth_rf,
                                        random_state=42,
                                        n_jobs=-1)
            model = TransformedTargetRegressor(regressor=rf , transformer=pt)

        elif model_name == "GB":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,200)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",0,1)
            max_depth_gb = trial.suggest_int("max_depth_gb",2,20)
            gb = GradientBoostingRegressor(n_estimators=n_estimators_gb,
                                                learning_rate=learning_rate_gb,
                                                max_depth=max_depth_gb,
                                                random_state=42)
            model = TransformedTargetRegressor(regressor=gb , transformer=pt)

        elif model_name == "KNN":
            n_neighbors_knn = trial.suggest_int("n_neighbors_knn",1,25)
            weights_knn = trial.suggest_categorical("weights_knn",["uniform","distance"])
            knn = KNeighborsRegressor(n_neighbors=n_neighbors_knn,
                                        weights=weights_knn,n_jobs=-1)
            model = TransformedTargetRegressor(regressor=knn , transformer=pt)

        elif model_name == "XGB":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,200)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",0.1,0.5)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",2,20)
            xgb = XGBRegressor(n_estimators=n_estimators_xgb,
                                    learning_rate=learning_rate_xgb,
                                    max_depth=max_depth_xgb,
                                    random_state=42,
                                    n_jobs=-1)
            model = TransformedTargetRegressor(regressor=xgb , transformer=pt)

        elif model_name == "LGBM":
            n_estimators_lgbm = trial.suggest_int("n_estimators_lgbm",10,200)
            learning_rate_lgbm = trial.suggest_float("learning_rate_lgbm",0.1,0.5)
            max_depth_lgbm = trial.suggest_int("max_depth_lgbm",2,20)
            lgbm = LGBMRegressor(n_estimators=n_estimators_lgbm,
                                    learning_rate=learning_rate_lgbm,
                                    max_depth=max_depth_lgbm,
                                    random_state=42)
            model = TransformedTargetRegressor(regressor=lgbm , transformer=pt)


        model.fit(X_train_trans , y_train)


        # log params
        mlflow.log_params(trial.params)
        mlflow.log_param("model_type" , model_name)

        

        # get the predictions
        y_pred_test = model.predict(X_test_trans)

        # calculate the error
        error = mean_absolute_error(y_test,y_pred_test)

        # log model_name
        mlflow.log_param("model",model_name)

        # log error
        mlflow.log_metric("MAE",error)

        return error

In [20]:
# create optuna study
study = optuna.create_study(direction="minimize",study_name="model_selection")

with mlflow.start_run(run_name="Best Model") as parent:
    # optimize the objective function
    study.optimize(objective,n_trials=30,n_jobs=-1)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

[I 2026-07-05 20:33:51,212] A new study created in memory with name: model_selection

🏃 View run clean-rook-914 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/392d6868a6134b2eaa7a93c8f7292370
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:34:16,714] Trial 8 finished with value: 4.782582107120026 and parameters: {'model': 'RF', 'n_estimators_rf': 20, 'max_depth_rf': 4}. Best is trial 8 with value: 4.782582107120026.

🏃 View run youthful-bass-38 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/3cf2b512ceeb45be8888d27806c22b5d
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run classy-lamb-534 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/4ce6ff3a42ba47ed93ec2e091027d81f
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run crawling-sow-987 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/453befb50c2e45f3a9b41fe45632dc6a
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-05 20:35:08,089] Trial 1 finished with value: 3.0475403643017533 and parameters: {'model': 'RF', 'n_estimators_rf': 134, 'max_depth_rf': 13}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run chill-duck-572 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/10545d64a36e4d09ab48c602fe3323b1
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:35:12,108] Trial 6 finished with value: 3.6741433143615723 and parameters: {'model': 'XGB', 'n_estimators_xgb': 193, 'learning_rate_xgb': 0.15519143202757105, 'max_depth_xgb': 2}. Best is trial 1 with value: 3.0475403643017533.
C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run bold-squirrel-45 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/538d851ebf7f4f128c395ca2346e1aab
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
[I 2026-07-05 20:35:28,287] Trial 7 finished with value: 4.497655225346525 and parameters: {'model': 'KNN', 'n_neighbors_knn': 22, 'weights_knn': 'distance'}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run big-donkey-446 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/9c6ebf4f6d54438d8a179b8f320359d9
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run able-bat-537 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/cc0e995eafaf46269170d62f7057b35b
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:35:44,714] Trial 5 finished with value: 4.500945890798475 and parameters: {'model': 'KNN', 'n_neighbors_knn': 10, 'weights_knn': 'uniform'}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:35:48,256] Trial 9 finished with value: 3.063137295742347 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 75, 'learning_rate_lgbm': 0.30235532278069444, 'max_depth_lgbm': 16}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run resilient-skink-524 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/e8fd1ecf2384463bb24fc75bc83b9522
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:35:56,130] Trial 15 finished with value: 3.3663032054901123 and parameters: {'model': 'XGB', 'n_estimators_xgb': 182, 'learning_rate_xgb': 0.455630955533218, 'max_depth_xgb': 18}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run bright-doe-24 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/37c63fa8785247c698584cc2ed8921b7
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:36:00,750] Trial 0 finished with value: 4.470294047596477 and parameters: {'model': 'KNN', 'n_neighbors_knn': 12, 'weights_knn': 'distance'}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:36:04,108] Trial 14 finished with value: 3.1245931662390576 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 185, 'learning_rate_lgbm': 0.3203270840757715, 'max_depth_lgbm': 15}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run wise-squid-77 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/ad39c1189c32401b8122f54199bb13a7
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:36:08,122] Trial 11 finished with value: 3.689224360847685 and parameters: {'model': 'GB', 'n_estimators_gb': 28, 'learning_rate_gb': 0.04074631064649836, 'max_depth_gb': 10}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:36:16,825] Trial 13 finished with value: 3.3383234691199544 and parameters: {'model': 'GB', 'n_estimators_gb': 26, 'learning_rate_gb': 0.8399285668836765, 'max_depth_gb': 6}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run honorable-turtle-243 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/e00b0d00f72640a38b9f34425f86e074
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run beautiful-hound-765 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/7cf3895a357143068987cedf20b49830
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run spiffy-ape-301 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/946f708d61c34a14945e88d1770abec1
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run bedecked-ant-304 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/5996b1b9bfe14a4397d294f48e62177f
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run traveling-calf-669 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/950199c2c8cc410ebf93f1c6008e1c05
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:37:02,598] Trial 16 finished with value: 3.095566438488191 and parameters: {'model': 'RF', 'n_estimators_rf': 22, 'max_depth_rf': 16}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:37:04,749] Trial 4 finished with value: 3.050769847514947 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 89, 'learning_rate_lgbm': 0.13493995745563017, 'max_depth_lgbm': 20}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:37:08,957] Trial 2 finished with value: 3.0478064288396904 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 35, 'learning_rate_lgbm': 0.33378816708276215, 'max_depth_lgbm': 11}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:37:12,754] Trial 10 finished with value: 3.263047456741333 and parameters: {'model': 'XGB', 'n_estimators_xgb': 128, 'learning_rate_xgb': 0.28126496432168435, 'max_depth_xgb': 17}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:37:16,937] Trial 12 finished with value: 3.2386638656761817 and parameters: {'model': 'GB', 'n_estimators_gb': 34, 'learning_rate_gb': 0.35698503882298127, 'max_depth_gb': 11}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run worried-croc-818 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/10dab554ef5746aa88213ca1e0f7546b
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:37:30,359] Trial 17 finished with value: 3.0617189621153003 and parameters: {'model': 'RF', 'n_estimators_rf': 106, 'max_depth_rf': 18}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run traveling-ram-589 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/d545eea3a73e46108705efab3fc4fba6
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:37:37,417] Trial 25 finished with value: 3.0588485075557714 and parameters: {'model': 'RF', 'n_estimators_rf': 197, 'max_depth_rf': 18}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run fun-jay-183 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/39c33a08b4f94d03a147505c55d4866a
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:37:44,891] Trial 26 finished with value: 3.064925777393575 and parameters: {'model': 'RF', 'n_estimators_rf': 195, 'max_depth_rf': 20}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run capable-finch-656 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/ca2237d0a0784612859d2b73f27121e5
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:37:57,994] Trial 19 finished with value: 3.063585040013037 and parameters: {'model': 'RF', 'n_estimators_rf': 172, 'max_depth_rf': 20}. Best is trial 1 with value: 3.0475403643017533.
C:\Users\LeoML\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

🏃 View run valuable-turtle-822 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/50e4af6f94e54fadb53dc6207cbd0404
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:38:16,941] Trial 21 finished with value: 3.0652862389002142 and parameters: {'model': 'RF', 'n_estimators_rf': 200, 'max_depth_rf': 20}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run kindly-shoat-885 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/f9c1506bd07e4a15969705ca0ec99e38
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4
🏃 View run mysterious-kit-827 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/c70b7f94bb9148fab906ad8e4539d634
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:38:30,048] Trial 22 finished with value: 3.059103762985661 and parameters: {'model': 'RF', 'n_estimators_rf': 199, 'max_depth_rf': 18}. Best is trial 1 with value: 3.0475403643017533.
[I 2026-07-05 20:38:32,815] Trial 27 finished with value: 3.1965796270844473 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 13, 'learning_rate_lgbm': 0.20882692510665268, 'max_depth_lgbm': 20}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run nimble-elk-273 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/163fd64d9a594903822281979955119f
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:43:16,256] Trial 29 finished with value: 7.390529880824584 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 0.6559844513325856, 'gamma_rbf': 2.981592207252057}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run fun-dove-606 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/593f15cf7b354ef5bde91a133e075f8a
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:44:22,579] Trial 3 finished with value: 4.567462705943621 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 5.874607386134636}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run abundant-horse-662 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/9924d606ce424c99bc9fc60a4c194db1
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:44:56,503] Trial 28 finished with value: 4.568022239407455 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 3.556316579668413}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run delicate-pig-757 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/21c4da44d4d144879dc7d667fda81f12
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:48:50,896] Trial 18 finished with value: 6.24605402343986 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 42.48333445122573, 'gamma_rbf': 0.4754255465009205}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run inquisitive-ray-532 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/f610d7b785ae46a4a86def2bfc1a8360
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:50:21,316] Trial 24 finished with value: 7.432145072303096 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 54.26485404419067, 'gamma_rbf': 5.006644756574547}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run salty-shrimp-597 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/b944da2ed99f4d34aabb7d3e96088b2a
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 20:52:47,650] Trial 20 finished with value: 3.766438265497936 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 7.538524998480884, 'degree_poly': 3}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run funny-snake-497 at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/e37e6c5ceddf4be989f8eb09c30d5590
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

[I 2026-07-05 21:09:00,581] Trial 23 finished with value: 4.101604707753101 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 8.311534140296699, 'degree_poly': 5}. Best is trial 1 with value: 3.0475403643017533.

🏃 View run Best Model at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4/runs/9339610540884375b28fd2e0e5a6eb94
🧪 View experiment at: https://dagshub.com/mridul0010/food-delivery-time-prediction.mlflow/#/experiments/4

In [21]:
study.best_value

3.0475403643017533

In [22]:
study.best_params

{'model': 'RF', 'n_estimators_rf': 134, 'max_depth_rf': 13}

In [23]:
study.trials_dataframe().head()

,number,value,datetime_start,datetime_complete,duration,params_c_linear,params_c_poly,params_c_rbf,params_degree_poly,params_gamma_rbf,params_kernel_svm,params_learning_rate_gb,params_learning_rate_lgbm,params_learning_rate_xgb,params_max_depth_gb,params_max_depth_lgbm,params_max_depth_rf,params_max_depth_xgb,params_model,params_n_estimators_gb,params_n_estimators_lgbm,params_n_estimators_rf,params_n_estimators_xgb,params_n_neighbors_knn,params_weights_knn,state
0,0,4.470294,2026-07-05 20:33:52.275037,2026-07-05 20:36:00.750280,0 days 00:02:08.475243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KNN,NaN,NaN,NaN,NaN,12.0,distance,COMPLETE
1,1,3.047540,2026-07-05 20:33:52.275830,2026-07-05 20:35:08.088966,0 days 00:01:15.813136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,RF,NaN,NaN,134.0,NaN,NaN,NaN,COMPLETE
2,2,3.047806,2026-07-05 20:33:52.276544,2026-07-05 20:37:08.957801,0 days 00:03:16.681257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.333788,NaN,NaN,11.0,NaN,NaN,LGBM,NaN,35.0,NaN,NaN,NaN,NaN,COMPLETE
3,3,4.567463,2026-07-05 20:33:52.276811,2026-07-05 20:44:22.579407,0 days 00:10:30.302596,5.874607,NaN,NaN,NaN,NaN,linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,3.050770,2026-07-05 20:33:52.277376,2026-07-05 20:37:04.749278,0 days 00:03:12.471902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.134940,NaN,NaN,20.0,NaN,NaN,LGBM,NaN,89.0,NaN,NaN,NaN,NaN,COMPLETE

In [24]:
study.trials_dataframe()['params_model'].value_counts()

params_model
RF      9
SVM     7
LGBM    5
KNN     3
XGB     3
GB      3
Name: count, dtype: int64

In [30]:
study.best_params

{'model': 'RF', 'n_estimators_rf': 134, 'max_depth_rf': 13}

In [33]:
best_xgb = RandomForestRegressor(n_estimators =  134, max_depth =  13)

model = TransformedTargetRegressor(regressor=best_xgb , transformer=pt)

model.fit(X_train_trans , y_train)

TransformedTargetRegressor(regressor=RandomForestRegressor(max_depth=13,
                                                           n_estimators=134),
                           transformer=PowerTransformer())

In [34]:
y_pred = model.predict(X_test_trans)

r2_score(y_test , y_pred)

0.8281715609240685

In [35]:
study.trials_dataframe().head()

,number,value,datetime_start,datetime_complete,duration,params_c_linear,params_c_poly,params_c_rbf,params_degree_poly,params_gamma_rbf,params_kernel_svm,params_learning_rate_gb,params_learning_rate_lgbm,params_learning_rate_xgb,params_max_depth_gb,params_max_depth_lgbm,params_max_depth_rf,params_max_depth_xgb,params_model,params_n_estimators_gb,params_n_estimators_lgbm,params_n_estimators_rf,params_n_estimators_xgb,params_n_neighbors_knn,params_weights_knn,state
0,0,4.470294,2026-07-05 20:33:52.275037,2026-07-05 20:36:00.750280,0 days 00:02:08.475243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KNN,NaN,NaN,NaN,NaN,12.0,distance,COMPLETE
1,1,3.047540,2026-07-05 20:33:52.275830,2026-07-05 20:35:08.088966,0 days 00:01:15.813136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,RF,NaN,NaN,134.0,NaN,NaN,NaN,COMPLETE
2,2,3.047806,2026-07-05 20:33:52.276544,2026-07-05 20:37:08.957801,0 days 00:03:16.681257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.333788,NaN,NaN,11.0,NaN,NaN,LGBM,NaN,35.0,NaN,NaN,NaN,NaN,COMPLETE
3,3,4.567463,2026-07-05 20:33:52.276811,2026-07-05 20:44:22.579407,0 days 00:10:30.302596,5.874607,NaN,NaN,NaN,NaN,linear,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,3.050770,2026-07-05 20:33:52.277376,2026-07-05 20:37:04.749278,0 days 00:03:12.471902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.134940,NaN,NaN,20.0,NaN,NaN,LGBM,NaN,89.0,NaN,NaN,NaN,NaN,COMPLETE

In [36]:
plot_optimization_history(study)